from apps.monitor.views.newsblur_app_servers import AppServers
from apps.monitor.views.newsblur_app_times import AppTimes
from apps.monitor.views.newsblur_classifiers import Classifiers
from apps.monitor.views.newsblur_dbtimes import DbTimes
from apps.monitor.views.newsblur_errors import Errors
from apps.monitor.views.newsblur_feed_counts import FeedCounts
from apps.monitor.views.newsblur_feed_sizes import FeedSizes
from apps.monitor.views.newsblur_feeds import Feeds
from apps.monitor.views.newsblur_loadtimes import LoadTimes
from apps.monitor.views.newsblur_stories import Stories
from apps.monitor.views.newsblur_tasks_codes import TasksCodes
from apps.monitor.views.newsblur_tasks_pipeline import TasksPipeline
from apps.monitor.views.newsblur_tasks_servers import TasksServers
from apps.monitor.views.newsblur_tasks_times import TasksTimes
from apps.monitor.views.newsblur_updates import Updates
from apps.monitor.views.newsblur_users import Users
