- name: Create base directories
  become: yes
  file: path="{{ item }}" state=directory
  with_items:
    - "/etc/letsencrypt"
    - "/var/lib/letsencrypt"
    - "/var/log/letsencrypt"

- name: pull certbot plugin docker image
  docker_image:
    state: present
    source: pull
    force_source: yes
    name: "certbot/certbot:{{ certbot_version }}"
  when: not use_dns_plugin|bool
  tags:
    - certbot

- name: run certbot plugin image
  docker_container:
    name: "certbot"
    image: "certbot/certbot:{{ certbot_version }}"
    state: started
    restart_policy: no
    force_kill: yes
    cleanup: yes
    detach: no
    auto_remove: yes
    volumes:
      - "/etc/letsencrypt:/etc/letsencrypt"
      - "/var/lib/letsencrypt:/var/lib/letsencrypt"
      - "/var/log/letsencrypt:/var/log/letsencrypt"
    command: >-
      certonly --standalone --agree-tos
      -m {{ letsencrypt_email }}
      -d {{ domains_list | join(' -d ') }}
    ports:
      - "80:80"
      - "443:443"
  when: not use_dns_plugin|bool
  tags:
    - certbot

- name: Add letsencrypt cronjob for cert renewal
  become: yes
  cron:
    name: letsencrypt_renewal
    minute: "0"
    hour: "0"
    day: "*"
    month: "*"
    weekday: "0"
    job: >-
      [ $(date +\%d) -le 07 ] &&
      docker pull certbot/certbot:{{ certbot_version }};
      service nginx stop;
      docker run --rm -it
      -v /etc/letsencrypt:/etc/letsencrypt
      -v /var/lib/letsencrypt:/var/lib/letsencrypt
      -v /var/log/letsencrypt:/var/log/letsencrypt
      -p 80:80
      -p 443:443
      certbot/certbot:{{ certbot_version }} renew;
      service nginx start
  when: not use_dns_plugin|bool
  tags:
    - certbot
