# Generated by Django 3.1.10 on 2026-01-29 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rss_feeds', '0011_auto_20250305_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_url', models.URLField(max_length=764)),
                ('feed_type', models.CharField(choices=[('youtube', 'YouTube'), ('reddit', 'Reddit'), ('newsletter', 'Newsletter'), ('podcast', 'Podcast')], db_index=True, max_length=20)),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('thumbnail_url', models.URLField(blank=True, default='', max_length=1000)),
                ('platform', models.CharField(blank=True, default='', max_length=50)),
                ('subscriber_count', models.IntegerField(default=0)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='popular_entries', to='rss_feeds.feed')),
            ],
            options={
                'ordering': ['feed_type', 'category', 'sort_order', '-subscriber_count'],
            },
        ),
        migrations.AddIndex(
            model_name='popularfeed',
            index=models.Index(fields=['feed_type', 'category'], name='discover_po_feed_ty_de5b4d_idx'),
        ),
        migrations.AddIndex(
            model_name='popularfeed',
            index=models.Index(fields=['feed_type', 'is_active'], name='discover_po_feed_ty_cefcbd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='popularfeed',
            unique_together={('feed_url', 'feed_type')},
        ),
    ]
