---
# File: main.yml - Handlers for Consul

- name: reload consul configuration
  become: yes
  service:
    name: consul
    state: reloaded
  listen: reload consul

- name: restart node
  become: yes
  command: docker restart node
  ignore_errors: yes
  listen: restart node
