http.port: 9200
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
http.cors.allow-credentials: true
xpack.security.enabled: false

discovery.type: single-node

cluster.routing.allocation.disk.threshold_enabled: false

cluster.name: "docker-cluster"
network.host: 0.0.0.0

