package com.newsblur.design

import androidx.compose.ui.graphics.Color

data class LoginShaderColors(
    val base: Color,
    val mid: Color,
    val light: Color,
    val gold: Color,
    val softGold: Color,
)

data class LoginAuthPalette(
    val shader: LoginShaderColors,
    val gradientTop: Color,
    val gradientBottom: Color,
    val scrimTop: Color,
    val scrimBottom: Color,
    val logoGlow: Color,
    val title: Color,
    val tagline: Color,
    val cardTop: Color,
    val cardBottom: Color,
    val cardBorder: Color,
    val cardShadow: Color,
    val segmentTrack: Color,
    val segmentPillTop: Color,
    val segmentPillBottom: Color,
    val segmentBorder: Color,
    val segmentSelectedText: Color,
    val segmentUnselectedText: Color,
    val fieldBackground: Color,
    val fieldBorder: Color,
    val fieldFocusBorder: Color,
    val fieldText: Color,
    val fieldPlaceholder: Color,
    val fieldCursor: Color,
    val button: Color,
    val buttonPressed: Color,
    val buttonDisabled: Color,
    val buttonText: Color,
    val error: Color,
    val link: Color,
    val footerBackground: Color,
    val footerBorder: Color,
    val footerText: Color,
    val footerSubtext: Color,
    val progressScrim: Color,
    val progressSurface: Color,
)

fun loginAuthPalette(variant: NbThemeVariant): LoginAuthPalette =
    when (variant) {
        NbThemeVariant.Light ->
            LoginAuthPalette(
                shader =
                    LoginShaderColors(
                        base = Color(0xFF1B2424),
                        mid = Color(0xFF3F5354),
                        light = Color(0xFF59898C),
                        gold = Color(0xFFD9A621),
                        softGold = Color(0xFFFBDB9B),
                    ),
                gradientTop = Color(0xFF506768),
                gradientBottom = Color(0xFF17201F),
                scrimTop = Color(0x22000000),
                scrimBottom = Color(0x6B081010),
                logoGlow = Color(0x80FBDB9B),
                title = White,
                tagline = Color(0xFFFBDB9B),
                cardTop = Color(0x29FFFFFF),
                cardBottom = Color(0x1AFFFFFF),
                cardBorder = Color(0x3DFFFFFF),
                cardShadow = Color(0x73000000),
                segmentTrack = Color(0x1AFFFFFF),
                segmentPillTop = Color(0x59FFFFFF),
                segmentPillBottom = Color(0x17FFFFFF),
                segmentBorder = Color(0x26FFFFFF),
                segmentSelectedText = White,
                segmentUnselectedText = Color(0x73FFFFFF),
                fieldBackground = Color(0x1AFFFFFF),
                fieldBorder = Color(0x26FFFFFF),
                fieldFocusBorder = Color(0x80D9A621),
                fieldText = White,
                fieldPlaceholder = Color(0x59FFFFFF),
                fieldCursor = Color(0xFFFBDB9B),
                button = Color(0xFFD9A621),
                buttonPressed = Color(0xFFB8890B),
                buttonDisabled = Color(0x80D9A621),
                buttonText = White,
                error = Color(0xFFF5A87A),
                link = Color(0xFFFBDB9B),
                footerBackground = Color(0x18FFFFFF),
                footerBorder = Color(0x24FFFFFF),
                footerText = White,
                footerSubtext = Color(0x99FFFFFF),
                progressScrim = Color(0x66000000),
                progressSurface = Color(0x3B0E1515),
            )

        NbThemeVariant.Sepia ->
            LoginAuthPalette(
                shader =
                    LoginShaderColors(
                        base = Color(0xFF32281F),
                        mid = Color(0xFF6D5843),
                        light = Color(0xFF8E765B),
                        gold = Color(0xFFD9A621),
                        softGold = Color(0xFFF2D19A),
                    ),
                gradientTop = Color(0xFF7A644D),
                gradientBottom = Color(0xFF211A15),
                scrimTop = Color(0x15000000),
                scrimBottom = Color(0x700D0804),
                logoGlow = Color(0x6EF2D19A),
                title = White,
                tagline = Color(0xFFF2D19A),
                cardTop = Color(0x2EFFF8F0),
                cardBottom = Color(0x18FFF8F0),
                cardBorder = Color(0x38FFF6E8),
                cardShadow = Color(0x73000000),
                segmentTrack = Color(0x16FFF8F0),
                segmentPillTop = Color(0x52FFF8F0),
                segmentPillBottom = Color(0x10FFF8F0),
                segmentBorder = Color(0x20FFF8F0),
                segmentSelectedText = White,
                segmentUnselectedText = Color(0x7AFFF8F0),
                fieldBackground = Color(0x16FFF8F0),
                fieldBorder = Color(0x24FFF8F0),
                fieldFocusBorder = Color(0x80D9A621),
                fieldText = White,
                fieldPlaceholder = Color(0x63FFF8F0),
                fieldCursor = Color(0xFFF2D19A),
                button = Color(0xFFD9A621),
                buttonPressed = Color(0xFFB8890B),
                buttonDisabled = Color(0x80D9A621),
                buttonText = White,
                error = Color(0xFFFFB996),
                link = Color(0xFFF2D19A),
                footerBackground = Color(0x18FFF8F0),
                footerBorder = Color(0x24FFF8F0),
                footerText = White,
                footerSubtext = Color(0x99FFF8F0),
                progressScrim = Color(0x66000000),
                progressSurface = Color(0x47241710),
            )

        NbThemeVariant.Dark ->
            LoginAuthPalette(
                shader =
                    LoginShaderColors(
                        base = Color(0xFF11191A),
                        mid = Color(0xFF294141),
                        light = Color(0xFF4C7476),
                        gold = Color(0xFFD9A621),
                        softGold = Color(0xFFF7DCA7),
                    ),
                gradientTop = Color(0xFF3F5354),
                gradientBottom = Color(0xFF0A1111),
                scrimTop = Color(0x18000000),
                scrimBottom = Color(0x7A030808),
                logoGlow = Color(0x70F7DCA7),
                title = White,
                tagline = Color(0xFFF7DCA7),
                cardTop = Color(0x24FFFFFF),
                cardBottom = Color(0x14FFFFFF),
                cardBorder = Color(0x30FFFFFF),
                cardShadow = Color(0x85000000),
                segmentTrack = Color(0x16FFFFFF),
                segmentPillTop = Color(0x50FFFFFF),
                segmentPillBottom = Color(0x10FFFFFF),
                segmentBorder = Color(0x22FFFFFF),
                segmentSelectedText = White,
                segmentUnselectedText = Color(0x73FFFFFF),
                fieldBackground = Color(0x16FFFFFF),
                fieldBorder = Color(0x20FFFFFF),
                fieldFocusBorder = Color(0x80D9A621),
                fieldText = White,
                fieldPlaceholder = Color(0x52FFFFFF),
                fieldCursor = Color(0xFFF7DCA7),
                button = Color(0xFFD9A621),
                buttonPressed = Color(0xFFB8890B),
                buttonDisabled = Color(0x80D9A621),
                buttonText = White,
                error = Color(0xFFF5A87A),
                link = Color(0xFFF7DCA7),
                footerBackground = Color(0x14FFFFFF),
                footerBorder = Color(0x20FFFFFF),
                footerText = White,
                footerSubtext = Color(0x99FFFFFF),
                progressScrim = Color(0x80000000),
                progressSurface = Color(0x4A0A1111),
            )

        NbThemeVariant.Black ->
            LoginAuthPalette(
                shader =
                    LoginShaderColors(
                        base = Black,
                        mid = Color(0xFF18292A),
                        light = Color(0xFF35595C),
                        gold = Color(0xFFD9A621),
                        softGold = Color(0xFFF7DCA7),
                    ),
                gradientTop = Color(0xFF223838),
                gradientBottom = Black,
                scrimTop = Color(0x12000000),
                scrimBottom = Color(0x8A000000),
                logoGlow = Color(0x63F7DCA7),
                title = White,
                tagline = Color(0xFFF7DCA7),
                cardTop = Color(0x20FFFFFF),
                cardBottom = Color(0x0FFFFFFF),
                cardBorder = Color(0x2AFFFFFF),
                cardShadow = Color(0x99000000),
                segmentTrack = Color(0x12FFFFFF),
                segmentPillTop = Color(0x46FFFFFF),
                segmentPillBottom = Color(0x0CFFFFFF),
                segmentBorder = Color(0x1CFFFFFF),
                segmentSelectedText = White,
                segmentUnselectedText = Color(0x73FFFFFF),
                fieldBackground = Color(0x12FFFFFF),
                fieldBorder = Color(0x1AFFFFFF),
                fieldFocusBorder = Color(0x80D9A621),
                fieldText = White,
                fieldPlaceholder = Color(0x52FFFFFF),
                fieldCursor = Color(0xFFF7DCA7),
                button = Color(0xFFD9A621),
                buttonPressed = Color(0xFFB8890B),
                buttonDisabled = Color(0x80D9A621),
                buttonText = White,
                error = Color(0xFFF5A87A),
                link = Color(0xFFF7DCA7),
                footerBackground = Color(0x12FFFFFF),
                footerBorder = Color(0x1CFFFFFF),
                footerText = White,
                footerSubtext = Color(0x99FFFFFF),
                progressScrim = Color(0xA3000000),
                progressSurface = Color(0x44000000),
            )

        NbThemeVariant.System -> loginAuthPalette(NbThemeVariant.Light)
    }

object LoginAuthPalettes {
    fun of(variant: NbThemeVariant): LoginAuthPalette = loginAuthPalette(variant)
}
