#!/srv/newsblur/venv/newsblur3/bin/python
# -*- coding: utf-8 -*-

from vendor.munin.pgbouncer import MuninPgBouncerPlugin

class MuninPgBouncerStatsQueryServerPlugin(MuninPgBouncerPlugin):
    command = "SHOW STATS"
    vlabel = "Microseconds"
    info = "Shows average query duration in microseconds"

    fields = (
        ('avg_query', dict(
            label = "received",
            info = "Average query duration",
            type = "GAUGE",
            min = "0",
        )),
    )

    @property
    def title(self):
        return "PgBouncer average query duration on %s" % self.dbwatched

if __name__ == "__main__":
    MuninPgBouncerStatsQueryServerPlugin().run()

