#!/usr/bin/env python

from munin.memcached import MuninMemcachedPlugin

class MuninMemcachedConnectionsPlugin(MuninMemcachedPlugin):
    title = "Memcached connections stats"
    args = "--base 1000"
    vlabel = "Connections"
    info = "connections stats"
    fields = (
        ('curr_connections', dict(
            label = "connections",
            info = "connections",
            type = "GAUGE",
        )),
    )

if __name__ == "__main__":
    MuninMemcachedConnectionsPlugin().run()
