#!/usr/bin/env python

from munin.memcached import MuninMemcachedPlugin

class MuninMemcachedCurrentItemsPlugin(MuninMemcachedPlugin):
    title = "Memcached current items stats"
    args = "--base 1000"
    vlabel = "Current Items"
    info = "current items stats"
    fields = (
        ('curr_items', dict(
            label = "items",
            info = "number current items",
            type = "GAUGE",
        )),
    )

if __name__ == "__main__":
    MuninMemcachedCurrentItemsPlugin().run()
