#!/srv/newsblur/venv/newsblur/bin/python
# -*- coding: utf-8 -*-

from vendor.munin.mongodb import MuninMongoDBPlugin

class MongoDBLockTime(MuninMongoDBPlugin):
    args = "-l 0 --base 1000"
    vlabel = "time"
    title = "MongoDB global lock time"
    info = "How long the global lock has been held"
    fields = (
        ('activeClients', dict(
            label = "Active clients",
            type = "COUNTER",
            min = "0",
        )),
        ('writers', dict(
            label = "Writers",
            type = "COUNTER",
            min = "0",
        )),
        ('readers', dict(
            label = "Readers",
            type = "COUNTER",
            min = "0",
        )),
    )

    def execute(self):
        status = self.connection.admin.command('serverStatus')
        try:
            active_clients = int(status["globalLock"]["activeClients"]["total"])
            readers = int(status["globalLock"]["activeClients"]["readers"])
            writers = int(status["globalLock"]["activeClients"]["writers"])
        except KeyError:
            active_clients = "U"
            readers = "U"
            writers = "U"
        return dict(activeClients=active_clients, readers=readers, writers=writers)

if __name__ == "__main__":
    MongoDBLockTime().run()
