#!/srv/newsblur/venv/newsblur3/bin/python
# -*- coding: utf-8 -*-
# vim: set sts=4 sw=4 encoding=utf-8

# Copyright (c) 2010, Rene Jochum
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the Rene Jochum nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.


from pymongo import Connection
import os

settings_host = os.environ.get("host", "127.0.0.1")
settings_port = 27017
settings_db = 'newsblur'

def getCollstats():
	global settings_host, settings_port, settings_db, settings_user, settings_password
        print locals(), settings_host, settings_port
	if settings_user and settings_password:
		settings_host = "%s:%s@%s" % (settings_user, settings_password, settings_host)
	con = Connection(settings_host, int(settings_port), slave_okay=True)
	db = con[settings_db]

	for coll in db.collection_names():
		if coll.startswith('system.'):
			continue
		stats = db.command("collstats", coll)
	        yield ("%s_size" % coll.replace('.', '_'), long(stats['totalIndexSize']),)

	con.disconnect()


def doData():
	for coll, stats in getCollstats():
		print "%s.value %s" % (coll, stats)


def doConfig():

    print "graph_title MongoDB collection index sizes"
    print "graph_args --base 1024 -l 0"
    print "graph_vlabel Kb"
    print "graph_category MongoDB"
    print "graph_total total"

    for k,v in getCollstats():
        print "%s.label %s" % (k, k)
        print "%s.min 0" % k
        print "%s.draw LINE1" % k


if __name__ == "__main__":
    from sys import argv
    from os import environ

    # Could be done by a for loop 
    # but i think if's are faster
    if 'HOST' in environ:
	settings_host = environ['HOST']
    if 'PORT' in environ:
	settings_port = environ['PORT']
    if 'DB' in environ:
        settings_db = environ['DB']
    if 'user' in environ:
        settings_user = environ['user']
    if 'password' in environ:
        settings_password = environ['password']
    print locals()
    if len(argv) > 1 and argv[1] == "config":
        doConfig()
    else:
        doData()
