#!/usr/bin/env python

from munin.redis import MuninRedisPlugin

class MuninRedisUsedMemoryPlugin(MuninRedisPlugin):
    title = "Redis used memory"
    args = "--base 1024"
    vlabel = "Memory"
    info = "used memory"
    fields = (
        ('used_memory', dict(
            label = "used memory",
            info = "used memory",
            type = "GAUGE",
        )),
    )

if __name__ == "__main__":
    MuninRedisUsedMemoryPlugin().run()
