#!/usr/bin/env python

from munin.redis import MuninRedisPlugin

class MuninRedisCommandsPlugin(MuninRedisPlugin):
    title = "Redis commands"
    args = "--base 1000"
    vlabel = "commands/sec"
    info = "total commands"
    fields = (
        ('total_commands_processed', dict(
            label = "commands",
            info = "commands",
            type = "COUNTER",
        )),
    )

if __name__ == "__main__":
    MuninRedisCommandsPlugin().run()
