#!/srv/newsblur/venv/newsblur3/bin/python

from vendor.munin.redis import MuninRedisPlugin

class MuninRedisTotalConnectionsPlugin(MuninRedisPlugin):
    title = "Redis connects"
    args = "--base 1000"
    vlabel = "connections/sec"
    info = "connections per second"
    fields = (
        ('total_connections_received', dict(
            label = "connections",
            info = "connections",
            type = "COUNTER",
        )),
    )

if __name__ == "__main__":
    MuninRedisTotalConnectionsPlugin().run()
