# Generated by Django 3.1.10 on 2026-01-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="auto_mark_read_days",
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
