# Generated by Django 3.1.10 on 2026-03-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reader", "0002_add_auto_mark_read_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersubscription",
            name="mute_expires_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
