# Generated by Django 3.1.10 on 2022-02-08 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0008_profile_paypal_sub_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaypalIds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_sub_id', models.CharField(blank=True, max_length=24, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paypal_ids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
