# Generated by Django 3.1.10 on 2022-02-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_paypalids'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_provider',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
