# Generated by Django 3.1.10 on 2025-12-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profile", "0020_profile_is_premium_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="grandfather_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
