# Generated by Django 3.1.10 on 2026-01-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0022_profile_is_grandfathered'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hide_trial_module',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
