# Generated by Django 3.1.10 on 2026-06-17 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0028_auto_20260519_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumPricingMigration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=24)),
                ('old_amount', models.IntegerField()),
                ('new_amount', models.IntegerField(default=36)),
                ('renewal_date_at_send', models.DateTimeField(blank=True, null=True)),
                ('email_sent_date', models.DateTimeField(blank=True, null=True)),
                ('price_switched_date', models.DateTimeField(blank=True, null=True)),
                ('paypal_canceled_date', models.DateTimeField(blank=True, null=True)),
                ('would_cancel_date', models.DateTimeField(blank=True, null=True)),
                ('resubscribed_date', models.DateTimeField(blank=True, null=True)),
                ('resubscribed_provider', models.CharField(blank=True, max_length=24, null=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('status_changed_date', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_migration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='premiumpricingmigration',
            index=models.Index(fields=['status'], name='profile_pre_status_27a7fe_idx'),
        ),
        migrations.AddIndex(
            model_name='premiumpricingmigration',
            index=models.Index(fields=['provider'], name='profile_pre_provide_8b8b8d_idx'),
        ),
    ]
