---
- name: Start node-exporter container
  become: yes
  docker_container:
    name: node-exporter
    image: prom/node-exporter
    container_default_behavior: no_defaults
    networks_cli_compatible: yes
    network_mode: default
    networks:
      - name: newsblurnet
    restart_policy: unless-stopped
    ports:
    - '9100:9100'
  notify: restart node-exporter

- name: Register node-exporter in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/node-exporter.json
  notify:
    - reload consul
  when: disable_consul_services_ie_staging is not defined
