/var/log/mongodb/*.log /var/log/mongodb_analytics/*.log {
       weekly
       rotate 10
       size 256M
       copytruncate
       delaycompress
       compress
       notifempty
       missingok
}
