---
- name: Ensure certificates directory exists
  file:
    path: /srv/newsblur/config/certificates
    state: directory

- name: Copy APNS key file (token-based authentication)
  copy:
    src: "/srv/secrets-newsblur/certificates/ios/apns_key.p8"
    dest: "/srv/newsblur/config/certificates/apns_key.p8"
    mode: 0400
