{
 "title": "ElasticSearch",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Free",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_mem_free_bytes"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_os_mem_used_bytes"
    }
   ]
  },
  {
   "title": "Bytes Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_transport_rx_size_bytes_total"
    }
   ]
  },
  {
   "title": "Total Packets Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_transport_rx_packets_total[$__interval])",
     "legendFormat": "Packets"
    }
   ]
  },
  {
   "title": "Number of Documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "elasticsearch_indices_docs", "legendFormat": "Documents" }
   ]
  },
  {
   "title": "Number of Documents",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs[1h])",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "title": "File System Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_filesystem_data_available_bytes",
     "legendFormat": "bytes free"
    },
    {
     "expr": "elasticsearch_filesystem_data_size_bytes",
     "legendFormat": "data size"
    }
   ]
  },
  {
   "title": "Process CPU Percent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_process_cpu_percent"
    }
   ]
  }
 ]
}