{
 "title": "New Mongo",
 "time": { "from": "2021-09-07T19:05:18.030Z", "to": "2021-09-07T20:02:21.742Z" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(mongo_objects, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Page Queues",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongo_page_queues{instance=\"$instance\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongo_page_faults{instance=\"$instance\"}",
     "legendFormat": "Page Faults"
    }
   ]
  },
  {
   "title": "Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "mongo_db_size{instance=\"$instance\"}",
     "legendFormat": "DB Size in Bytes"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongo_objects{instance=~\"$instance\"}",
     "legendFormat": "Number of Objects"
    }
   ]
  },
  {
   "title": "Ops",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mongo_ops{instance=\"$instance\"}",
     "legendFormat": "{{ type }}"
    }
   ]
  }
 ]
}