{
 "title": "Postgres",
 "time": { "from": "2021-10-26T11:57:59.481Z", "to": "2021-10-26T14:21:53.820Z" },
 "panels": [
  {
   "title": "Row Counts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_tup_updated{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "rows updated"
    },
    {
     "expr": "rate(pg_stat_database_tup_fetched{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "rows fetched"
    },
    {
     "expr": "rate(pg_stat_database_tup_inserted{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "rows inserted"
    },
    {
     "expr": "rate(pg_stat_database_tup_returned{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "rows returned"
    },
    {}
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "pg_settings_block_size" }
   ]
  },
  {
   "title": "Conflicts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_conflicts{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "Database Conflicts"
    },
    {
     "expr": "rate(pg_stat_database_conflicts_confl_bufferpin{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "Canceled due to pinned buffers"
    },
    {
     "expr": "rate(pg_stat_database_conflicts_confl_deadlock{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "Canceled due to deadlocks"
    },
    {
     "expr": "rate(pg_stat_database_conflicts_confl_lock{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "Canceled due to lock timeouts"
    },
    {
     "expr": "rate(pg_stat_database_conflicts_confl_tablespace{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "Canceled due to dropped tablespaces"
    },
    {
     "expr": "rate(pg_stat_database_conflicts_confl_snapshot{datname=\"newsblur\"}[$__interval])",
     "legendFormat": "Cancelled due to old snapshots"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"postgres exporter\"}"
    }
   ]
  }
 ]
}