{
 "title": "Redis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(redis_active_connections, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_memory{instance=\"$instance\"}",
     "legendFormat": "{{ db }}"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "redis_used_memory{instance=\"$instance\"}",
     "legendFormat": "used memory"
    }
   ]
  },
  {
   "title": "Connections per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_connects{instance=\"$instance\"}[$__interval])",
     "legendFormat": "Connections per Second"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "redis_active_connections{instance=\"$instance\"}",
     "legendFormat": "active connections"
    }
   ]
  },
  {
   "title": "Redis Commands per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(redis_commands{instance=\"$instance\"}[1m])",
     "legendFormat": "Total Commands Processed"
    }
   ]
  },
  {
   "title": "Redis Size (keys)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " redis_size{instance=\"$instance\"}",
     "legendFormat": "{{ db }}"
    }
   ]
  }
 ]
}