---
- name: DEPLOY -> monitor
  hosts: db
  gather_facts: false
  vars_files:
    - ../env_vars/base.yml

  tasks:
    - name: Update Sentry release
      connection: local
      shell: >
        curl {{ sentry_monitor_release_webhook }}/ \
        -X POST \
        -H 'Content-Type: application/json' \
        -d '{"version": "{{ lookup('pipe', 'date "+%Y-%m-%d %H:%M:%S"') }}"}'

    - name: Pull newsblur_web github
      git:
        repo: https://github.com/samuelclay/NewsBlur.git
        dest: /srv/newsblur/
        version: master
      register: pulled
    
    - name: Reload monitor
      become: yes
      command: "docker restart monitor"
