---
- name: SETUP -> forum containers
  hosts: forum
  vars_files:
    - ../env_vars/base.yml
  vars:
    update_apt_cache: yes
    motd_role: app

  roles:
    - { role: "base", tags: "base" }
    - { role: "ufw", tags: "ufw" }
    - { role: "docker", tags: "docker" }
    - { role: "repo", tags: ["repo", "pull"] }
    - { role: "dnsmasq", tags: "dnsmasq" }
    - { role: "consul", tags: "consul" }
    - { role: "consul-client", tags: "consul" }

    - { role: "forum", tags: "forum" }
    - { role: "node-exporter", tags: ["node-exporter", "metrics"] }
