package com.newsblur.discover

// GoogleNewsCatalog.kt mirrors the iOS DiscoverSitesModels.swift topic catalog.
object GoogleNewsCatalog {
    val categories =
        linkedMapOf(
            "Anime & Manga" to
                listOf(
                    "Anime Awards",
                    "Anime Conventions",
                    "Anime Dubs",
                    "Anime Fan Art",
                    "Anime Figurines",
                    "Anime Film Releases",
                    "Anime Gaming",
                    "Anime Industry",
                    "Anime Merchandise",
                    "Anime Movie Box Office",
                    "Anime Season Preview",
                    "Anime Soundtrack",
                    "Anime Streaming News",
                    "Anime Studio News",
                    "Anime Voice Actors",
                    "Cosplay",
                    "Fantasy Anime",
                    "Horror Manga",
                    "Isekai Anime",
                    "Josei Manga",
                    "Light Novel Adaptations",
                    "Magical Girl Anime",
                    "Manga Adaptations",
                    "Manga Artists",
                    "Manga Collectors",
                    "Manga Sales Charts",
                    "Manhwa",
                    "Mecha Anime",
                    "Romance Manga",
                    "Sci-Fi Anime",
                    "Seinen Anime",
                    "Shojo Manga",
                    "Shonen Anime",
                    "Shonen Jump",
                    "Slice of Life Anime",
                    "Sports Anime",
                    "Webtoon",
                ),
            "Architecture" to
                listOf(
                    "3D Printed Buildings",
                    "Adaptive Reuse",
                    "Affordable Housing Design",
                    "Airport Architecture",
                    "Architectural Photography",
                    "Architectural Visualization",
                    "Art Deco Architecture",
                    "Biophilic Design",
                    "Brutalist Architecture",
                    "Building Information Modeling",
                    "Deconstructivism",
                    "Floating Architecture",
                    "Gothic Architecture",
                    "Green Building Design",
                    "Historic Preservation",
                    "Interior Architecture",
                    "Landscape Architecture",
                    "LEED Certification",
                    "Mass Timber Construction",
                    "Modernist Architecture",
                    "Modular Construction",
                    "Museum Architecture",
                    "Net Zero Buildings",
                    "Parametric Design",
                    "Passive House Design",
                    "Prefab Architecture",
                    "Residential Architecture",
                    "Sacred Architecture",
                    "Skyscraper Design",
                    "Smart Buildings",
                    "Stadium Design",
                    "Sustainable Architecture",
                    "Tiny House Design",
                    "Urban Planning",
                    "Vernacular Architecture",
                ),
            "Arts & Culture" to
                listOf(
                    "Animation & Motion Graphics",
                    "Art Auctions",
                    "Art Criticism",
                    "Art Exhibitions",
                    "Art History",
                    "Art Market",
                    "Art Restoration",
                    "Art Theft & Repatriation",
                    "Arts Education",
                    "Arts Funding & Grants",
                    "Ballet & Dance",
                    "Biennials & Art Fairs",
                    "Ceramics & Pottery",
                    "Contemporary Art",
                    "Cultural Heritage",
                    "Cultural Policy",
                    "Digital Art & NFTs",
                    "Film Festivals",
                    "Folk Art & Crafts",
                    "Galleries",
                    "Illustration & Comics",
                    "Indigenous Art",
                    "Literary Fiction",
                    "Museum News",
                    "Opera",
                    "Performing Arts",
                    "Poetry",
                    "Public Art & Murals",
                    "Sculpture",
                    "Street Art & Graffiti",
                    "Textile Arts",
                    "Theater & Broadway",
                ),
            "Automotive" to
                listOf(
                    "Auto Shows",
                    "Automotive Industry",
                    "Autonomous Vehicles",
                    "BMW",
                    "Budget Cars",
                    "BYD",
                    "Car Design",
                    "Car Insurance",
                    "Car Maintenance Tips",
                    "Car Reviews",
                    "Car Safety Recalls",
                    "Car Technology",
                    "Connected Cars",
                    "Electric Trucks",
                    "Electric Vehicles",
                    "Ferrari",
                    "Ford",
                    "Formula 1",
                    "Fuel Economy",
                    "Honda",
                    "Hybrid Vehicles",
                    "Hyundai",
                    "Luxury Cars",
                    "Mercedes-Benz",
                    "Minivans",
                    "Motorcycle News",
                    "NASCAR",
                    "Off-Road Vehicles",
                    "Pickup Trucks",
                    "Porsche",
                    "Rivian",
                    "Self-Driving Cars",
                    "Sports Cars",
                    "SUVs",
                    "Tesla",
                    "Toyota",
                    "Used Cars",
                ),
            "Books & Reading" to
                listOf(
                    "Audiobooks",
                    "Author Interviews",
                    "Bestsellers",
                    "Book Adaptations",
                    "Book Bans and Censorship",
                    "Book Clubs",
                    "Book Fairs and Festivals",
                    "Book Recommendations",
                    "Book Reviews",
                    "Bookstores",
                    "Children's Books",
                    "Classic Literature",
                    "Comic Books",
                    "Ebooks and Digital Reading",
                    "Fantasy Books",
                    "Graphic Novels",
                    "Historical Fiction",
                    "Horror Books",
                    "Indie Publishing",
                    "Libraries",
                    "Literary Awards",
                    "Literary Fiction",
                    "Memoir and Autobiography",
                    "Mystery Books",
                    "New Book Releases",
                    "Nonfiction Books",
                    "Poetry",
                    "Publishing Industry",
                    "Reading and Literacy",
                    "Romance Books",
                    "Science Fiction Books",
                    "Self-Help Books",
                    "Self-Publishing",
                    "Thriller Books",
                    "True Crime Books",
                    "Young Adult Books",
                ),
            "Business" to
                listOf(
                    "B2B",
                    "Bankruptcy",
                    "Branding",
                    "Business Analytics",
                    "Business Development",
                    "Business Ethics",
                    "Business Intelligence",
                    "Business Law",
                    "Commercial Real Estate",
                    "Competitive Analysis",
                    "Consulting",
                    "Corporate Finance",
                    "Corporate Governance",
                    "Corporate Social Responsibility",
                    "Corporate Strategy",
                    "Digital Transformation",
                    "E-Commerce",
                    "Executive Leadership",
                    "Family Business",
                    "Franchising",
                    "Human Resources",
                    "IPO",
                    "Logistics",
                    "Management",
                    "Market Research",
                    "Mergers and Acquisitions",
                    "Outsourcing",
                    "Private Equity",
                    "Procurement",
                    "Retail",
                    "Revenue Growth",
                    "Risk Management",
                    "Sales Strategy",
                    "Small Business",
                    "Supply Chain",
                    "Venture Capital",
                    "Workplace Culture",
                ),
            "Career & Job Market" to
                listOf(
                    "AI Replacing Jobs",
                    "Apprenticeship Programs",
                    "Career Change Advice",
                    "Career Coaching",
                    "Diversity Hiring",
                    "Employee Benefits Trends",
                    "Employment Law Changes",
                    "Four Day Work Week",
                    "Freelancing Opportunities",
                    "Gig Economy",
                    "Hiring Trends",
                    "Industry Job Growth",
                    "Internship Opportunities",
                    "Job Interview Tips",
                    "Job Market for Graduates",
                    "Job Market Outlook",
                    "Job Search Strategies",
                    "Labor Market Data",
                    "LinkedIn Networking",
                    "Minimum Wage Debate",
                    "Professional Certifications",
                    "Quiet Quitting",
                    "Remote Work Trends",
                    "Resume Writing Tips",
                    "Return to Office",
                    "Salary Negotiation",
                    "Side Hustle Ideas",
                    "Skills Development",
                    "Startup Hiring",
                    "Tech Layoffs",
                    "Unemployment Rate",
                    "Union Labor News",
                    "Upskilling and Reskilling",
                    "Work-Life Balance",
                    "Worker Burnout",
                    "Workplace AI Tools",
                    "Workplace Culture",
                    "Workplace Harassment",
                    "Workplace Mental Health",
                ),
            "Comedy & Humor" to
                listOf(
                    "Absurdist Humor",
                    "Comedian News",
                    "Comedy Awards",
                    "Comedy Clubs",
                    "Comedy Festivals",
                    "Comedy Movies",
                    "Comedy Podcasts",
                    "Comedy Roasts",
                    "Comedy Specials",
                    "Comedy Streaming",
                    "Comedy Tours",
                    "Comedy Variety Shows",
                    "Comedy Writing",
                    "Comic Strips",
                    "Dark Humor",
                    "Funny Videos",
                    "Improv Comedy",
                    "Late Night TV",
                    "Memes",
                    "Musical Comedy",
                    "Parody",
                    "Political Satire",
                    "Romantic Comedy",
                    "Satire",
                    "Sitcoms",
                    "Sketch Comedy",
                    "Slapstick Comedy",
                    "SNL Saturday Night Live",
                    "Stand-Up Comedy",
                    "Web Comedy Series",
                ),
            "Cryptocurrency & Web3" to
                listOf(
                    "Airdrop Token Launch",
                    "Avalanche AVAX",
                    "Bitcoin",
                    "Bitcoin ETF",
                    "Bitcoin Halving",
                    "Bitcoin Mining",
                    "Blockchain Technology",
                    "Cardano",
                    "Central Bank Digital Currency",
                    "Chainlink",
                    "Cross Chain Interoperability",
                    "Crypto Lending",
                    "Crypto Regulation",
                    "Crypto Scam Fraud",
                    "Crypto Venture Capital",
                    "Crypto Wallet Security",
                    "Cryptocurrency Exchange",
                    "Cryptocurrency Tax",
                    "DAO Governance",
                    "Decentralized Exchange",
                    "DeFi",
                    "Dogecoin",
                    "Ethereum",
                    "Ethereum Staking",
                    "GameFi",
                    "Layer 2 Scaling",
                    "Meme Coins",
                    "Metaverse Crypto",
                    "NFT Market",
                    "Polkadot",
                    "Polygon MATIC",
                    "Proof of Stake",
                    "Smart Contracts",
                    "Solana",
                    "Stablecoins",
                    "Tokenization",
                    "Web3 Development",
                    "XRP Ripple",
                    "Yield Farming",
                    "Zero Knowledge Proofs",
                ),
            "DIY & Crafts" to
                listOf(
                    "3D Printing",
                    "Basket Weaving",
                    "Calligraphy",
                    "Candle Making",
                    "Ceramics",
                    "CNC Machining",
                    "Crochet",
                    "Cross Stitch",
                    "Electronics Projects",
                    "Embroidery",
                    "Epoxy Projects",
                    "Furniture Building",
                    "Gardening DIY",
                    "Home Improvement",
                    "Home Renovation",
                    "Jewelry Making",
                    "Knitting",
                    "Laser Cutting",
                    "Leatherwork",
                    "Macrame",
                    "Metalworking",
                    "Mosaic Art",
                    "Origami",
                    "Painting Techniques",
                    "Paper Crafts",
                    "Pottery",
                    "Pyrography",
                    "Quilting",
                    "Resin Art",
                    "Scrapbooking",
                    "Sewing",
                    "Soap Making",
                    "Stained Glass",
                    "Textile Dyeing",
                    "Upcycling",
                    "Weaving",
                    "Welding Projects",
                    "Woodworking",
                ),
            "Data Science & Analytics" to
                listOf(
                    "A/B Testing",
                    "Anomaly Detection",
                    "AutoML",
                    "Bayesian Statistics",
                    "Big Data Analytics",
                    "Business Intelligence",
                    "Causal Inference",
                    "Computer Vision",
                    "Data Engineering",
                    "Data Governance",
                    "Data Lakehouse",
                    "Data Mining",
                    "Data Visualization",
                    "Data Warehousing",
                    "Deep Learning",
                    "Edge AI",
                    "ETL Pipelines",
                    "Feature Engineering",
                    "Federated Learning",
                    "Generative AI",
                    "Graph Neural Networks",
                    "Image Recognition",
                    "Large Language Models",
                    "Machine Learning",
                    "MLOps",
                    "Natural Language Processing",
                    "Neural Networks",
                    "Predictive Analytics",
                    "Real-Time Analytics",
                    "Recommendation Systems",
                    "Reinforcement Learning",
                    "Responsible AI",
                    "Speech Recognition",
                    "Statistical Modeling",
                    "Synthetic Data",
                    "Text Mining",
                    "Time Series Analysis",
                    "Vector Databases",
                ),
            "Design" to
                listOf(
                    "3D Design",
                    "Accessibility Design",
                    "Animation Design",
                    "Automotive Design",
                    "Branding",
                    "Color Theory",
                    "Data Visualization",
                    "Design Leadership",
                    "Design Systems",
                    "Design Thinking",
                    "Design Tools",
                    "Environmental Design",
                    "Fashion Design",
                    "Figma",
                    "Furniture Design",
                    "Game Design",
                    "Graphic Design",
                    "Illustration",
                    "Industrial Design",
                    "Information Architecture",
                    "Interaction Design",
                    "Interior Design",
                    "Logo Design",
                    "Material Design",
                    "Motion Graphics",
                    "Package Design",
                    "Print Design",
                    "Product Design",
                    "Responsive Design",
                    "Service Design",
                    "Sound Design",
                    "Sustainable Design",
                    "Typography",
                    "UI Design",
                    "UX Design",
                    "UX Research",
                    "Visual Design",
                    "Web Design",
                ),
            "Economics" to
                listOf(
                    "Antitrust Economics",
                    "Behavioral Economics",
                    "Central Banking",
                    "Consumer Spending",
                    "Cost of Living",
                    "Deglobalization",
                    "Development Economics",
                    "Economic Forecasting",
                    "Economic Mobility",
                    "Economic Recession",
                    "Economic Sanctions",
                    "Emerging Markets",
                    "Federal Reserve",
                    "Fiscal Policy",
                    "GDP Growth",
                    "Gig Economy",
                    "Government Spending",
                    "Green Economy",
                    "Housing Market Economics",
                    "Income Inequality",
                    "Industrial Policy",
                    "Inflation",
                    "Interest Rates",
                    "International Trade",
                    "Labor Economics",
                    "Macroeconomics",
                    "Microeconomics",
                    "Monetary Policy",
                    "National Debt",
                    "Public Finance",
                    "Stagflation",
                    "Supply Chain Economics",
                    "Tariffs",
                    "Tax Policy",
                    "Trade Policy",
                    "Unemployment",
                    "Wage Growth",
                    "Wealth Gap",
                ),
            "Education" to
                listOf(
                    "Adult Education",
                    "Charter Schools",
                    "Classroom Technology",
                    "College Admissions",
                    "Community College",
                    "Curriculum Development",
                    "Distance Learning",
                    "Early Childhood Education",
                    "EdTech",
                    "Education Equity",
                    "Education Funding",
                    "Education Policy",
                    "Education Reform",
                    "Education Technology",
                    "Financial Aid",
                    "Graduate School",
                    "Higher Education",
                    "Homeschooling",
                    "K-12 Education",
                    "Literacy",
                    "Online Learning",
                    "Private Schools",
                    "Public Schools",
                    "School Board",
                    "School Choice",
                    "School Safety",
                    "Special Education",
                    "Standardized Testing",
                    "STEM Education",
                    "Student Loans",
                    "Student Mental Health",
                    "Study Abroad",
                    "Teacher Shortage",
                    "Teaching Methods",
                    "Trade Schools",
                    "Tutoring",
                    "University Research",
                    "Vocational Training",
                ),
            "Entertainment" to
                listOf(
                    "Animation",
                    "Awards Shows",
                    "Bollywood",
                    "Box Office",
                    "Broadway",
                    "Casting News",
                    "Celebrity Gossip",
                    "Celebrity News",
                    "Concert Tours",
                    "Disney Plus",
                    "Documentaries",
                    "Emmy Awards",
                    "Entertainment Industry",
                    "Film Festivals",
                    "Golden Globes",
                    "Grammy Awards",
                    "HBO",
                    "Hollywood",
                    "K-Drama",
                    "Late Night TV",
                    "Movie Reviews",
                    "Movie Trailers",
                    "Movies",
                    "Music Videos",
                    "Netflix",
                    "Oscars",
                    "Reality TV",
                    "Red Carpet",
                    "Stand-Up Comedy",
                    "Streaming",
                    "Talk Shows",
                    "Theme Parks",
                    "TV Ratings",
                    "TV Shows",
                    "Variety Shows",
                ),
            "Entrepreneurship & Startups" to
                listOf(
                    "AI Startups",
                    "Angel Investors",
                    "Bootstrapped Startups",
                    "Climate Tech Startups",
                    "Corporate Venture Capital",
                    "Customer Acquisition",
                    "Deep Tech Startups",
                    "Fintech Startups",
                    "Growth Hacking",
                    "Healthtech Startups",
                    "Indie Hackers",
                    "Lean Startup Methodology",
                    "Pitch Deck Tips",
                    "Product-Market Fit",
                    "Remote Startup Teams",
                    "SaaS Startups",
                    "Scaling Startups",
                    "Seed Round Funding",
                    "Series A Funding",
                    "Solopreneur",
                    "Startup Accelerators",
                    "Startup Acquisitions",
                    "Startup Competitions",
                    "Startup Culture",
                    "Startup Equity and Vesting",
                    "Startup Exit Strategies",
                    "Startup Failure Post-Mortems",
                    "Startup Founder Stories",
                    "Startup Fundraising",
                    "Startup Incubators",
                    "Startup IPO",
                    "Startup Layoffs",
                    "Startup Metrics and KPIs",
                    "Startup Pivots",
                    "Startup Valuations",
                    "Techstars",
                    "Venture Capital Funding",
                    "Y Combinator",
                ),
            "Environment & Sustainability" to
                listOf(
                    "Air Pollution",
                    "Arctic Ice",
                    "Biodiversity",
                    "Carbon Capture",
                    "Carbon Emissions",
                    "Circular Economy",
                    "Climate Change",
                    "Climate Policy",
                    "Coral Reefs",
                    "Deforestation",
                    "Drought",
                    "Endangered Species",
                    "Environmental Justice",
                    "Environmental Policy",
                    "ESG Investing",
                    "Food Waste",
                    "Geothermal Energy",
                    "Global Warming",
                    "Green Energy Storage",
                    "Green Technology",
                    "Hydroelectric Power",
                    "Net Zero",
                    "Ocean Conservation",
                    "Organic Farming",
                    "Paris Agreement",
                    "Plastic Pollution",
                    "Recycling",
                    "Reforestation",
                    "Renewable Energy",
                    "Sea Level Rise",
                    "Solar Energy",
                    "Sustainable Agriculture",
                    "Sustainable Fashion",
                    "Waste Management",
                    "Water Conservation",
                    "Water Pollution",
                    "Wildfires",
                    "Wind Energy",
                ),
            "Fashion & Beauty" to
                listOf(
                    "Anti-Aging Skincare",
                    "Athleisure",
                    "Beauty Influencers",
                    "Beauty Tech",
                    "Bridal Fashion",
                    "Celebrity Style",
                    "Clean Beauty",
                    "Cosmetic Surgery",
                    "Denim Trends",
                    "Fashion Designers",
                    "Fashion E-Commerce",
                    "Fashion Photography",
                    "Fashion Sustainability",
                    "Fashion Week",
                    "Fast Fashion",
                    "Fragrance and Perfume",
                    "Hair Care",
                    "Hair Color Trends",
                    "Handbags and Accessories",
                    "Haute Couture",
                    "Jewelry Trends",
                    "K-Beauty",
                    "Luxury Fashion Brands",
                    "Makeup Trends",
                    "Men's Fashion",
                    "Nail Art",
                    "Plus Size Fashion",
                    "Red Carpet Fashion",
                    "Skincare Routine",
                    "Sneaker Culture",
                    "Streetwear",
                    "Sunglasses and Eyewear",
                    "Sustainable Fashion",
                    "Textile Innovation",
                    "Thrift and Resale Fashion",
                    "Vintage Fashion",
                    "Watch Collecting",
                    "Women's Fashion",
                ),
            "Finance" to
                listOf(
                    "401k",
                    "Banking",
                    "Bonds",
                    "Budgeting",
                    "Commodities",
                    "Corporate Earnings",
                    "Credit Cards",
                    "Credit Scores",
                    "Cryptocurrency",
                    "Day Trading",
                    "Estate Planning",
                    "ETFs",
                    "Federal Reserve",
                    "Financial Planning",
                    "Financial Regulation",
                    "Financial Technology",
                    "Fintech",
                    "Foreign Exchange",
                    "Hedge Funds",
                    "Index Funds",
                    "Inflation",
                    "Insurance",
                    "Interest Rates",
                    "Investing",
                    "IPOs",
                    "Mergers and Acquisitions",
                    "Mortgages",
                    "Mutual Funds",
                    "Personal Finance",
                    "Private Equity",
                    "Real Estate Investing",
                    "Retirement Planning",
                    "Robo-Advisors",
                    "Small Business Finance",
                    "Stock Market",
                    "Student Loans",
                    "Taxes",
                    "Venture Capital",
                    "Wall Street",
                    "Wealth Management",
                ),
            "Food & Cooking" to
                listOf(
                    "Baking and Pastry",
                    "Bread Baking",
                    "Celebrity Chefs",
                    "Cheese and Cheesemaking",
                    "Chinese Cuisine",
                    "Chocolate and Confections",
                    "Cocktails and Mixology",
                    "Coffee Culture",
                    "Comfort Food",
                    "Cooking Techniques",
                    "Craft Beer and Brewing",
                    "Desserts and Sweets",
                    "Farm to Table",
                    "Fermentation and Pickling",
                    "Food Photography",
                    "Food Preservation and Canning",
                    "Food Safety and Nutrition",
                    "Food Science",
                    "Food Trucks",
                    "French Cuisine",
                    "Grilling and BBQ",
                    "Indian Cuisine",
                    "Italian Cuisine",
                    "Japanese Cuisine",
                    "Korean Cuisine",
                    "Meal Prep",
                    "Mediterranean Cuisine",
                    "Mexican Cuisine",
                    "Middle Eastern Cuisine",
                    "Plant-Based Cooking",
                    "Restaurant Industry",
                    "Seafood",
                    "Sourdough",
                    "Spices and Seasoning",
                    "Street Food",
                    "Tea Culture",
                    "Thai Cuisine",
                    "Vegan Recipes",
                    "Wine and Sommelier",
                ),
            "Gaming" to
                listOf(
                    "Battle Royale Games",
                    "Cloud Gaming",
                    "Co-op Games",
                    "Competitive Gaming",
                    "Console Gaming",
                    "Esports",
                    "Fighting Games",
                    "FPS Games",
                    "Free to Play Games",
                    "Game Deals",
                    "Game Design",
                    "Game Emulation",
                    "Game Modding",
                    "Game Reviews",
                    "Game Soundtracks",
                    "Game Streaming",
                    "Gaming Accessories",
                    "Gaming Hardware",
                    "Horror Games",
                    "Indie Games",
                    "MMOs",
                    "Mobile Gaming",
                    "Nintendo",
                    "Open World Games",
                    "PC Gaming",
                    "PlayStation",
                    "Racing Games",
                    "Retro Gaming",
                    "Roguelike Games",
                    "RPGs",
                    "Simulation Games",
                    "Speedrunning",
                    "Sports Games",
                    "Steam",
                    "Strategy Games",
                    "Survival Games",
                    "Tabletop RPGs",
                    "VR Gaming",
                    "Xbox",
                ),
            "Health & Fitness" to
                listOf(
                    "Addiction Recovery",
                    "Bodybuilding",
                    "Cardio Fitness",
                    "Clinical Trials",
                    "CrossFit",
                    "Cycling & Biking",
                    "Diabetes Prevention",
                    "Functional Fitness",
                    "Gut Health & Microbiome",
                    "Heart Health",
                    "HIIT Workouts",
                    "Immune System",
                    "Intermittent Fasting",
                    "Keto Diet",
                    "Marathon Training",
                    "Meditation & Mindfulness",
                    "Mental Health & Wellness",
                    "Nutrition & Diet",
                    "Outdoor Fitness & Hiking",
                    "Physical Therapy",
                    "Pilates",
                    "Plant-Based Diet",
                    "Protein & Muscle Recovery",
                    "Public Health Policy",
                    "Running & Jogging",
                    "Senior Fitness",
                    "Sleep & Recovery",
                    "Sports Medicine",
                    "Stretching & Mobility",
                    "Supplements & Vitamins",
                    "Swimming",
                    "Wearable Fitness Technology",
                    "Weight Loss",
                    "Weightlifting",
                    "Women's Health",
                    "Yoga",
                ),
            "History" to
                listOf(
                    "African Kingdoms",
                    "Age of Exploration",
                    "American Revolution",
                    "Ancient China",
                    "Ancient Egypt",
                    "Ancient Greece",
                    "Ancient India",
                    "Ancient Mesopotamia",
                    "Ancient Rome",
                    "Archaeology",
                    "Art History",
                    "British Empire",
                    "Byzantine Empire",
                    "Civil Rights Movement",
                    "Civil War",
                    "Cold War",
                    "Colonial History",
                    "Crusades",
                    "Feudal Japan",
                    "French Revolution",
                    "Historical Preservation",
                    "History of Religion",
                    "History of Science",
                    "Holocaust",
                    "Industrial Revolution",
                    "Korean War",
                    "Latin American History",
                    "Medieval Europe",
                    "Mesoamerican Civilizations",
                    "Military History",
                    "Naval History",
                    "Oral History",
                    "Ottoman Empire",
                    "Renaissance",
                    "Russian Revolution",
                    "Silk Road",
                    "Vietnam War",
                    "Viking Age",
                    "World War I",
                    "World War II",
                ),
            "Hobbies & Collections" to
                listOf(
                    "Amateur Radio",
                    "Antique Collecting",
                    "Aquariums and Fishkeeping",
                    "Beekeeping",
                    "Birdwatching",
                    "Board Games",
                    "Card Games",
                    "Coin Collecting",
                    "Comic Books",
                    "Cosplay",
                    "Drone Flying",
                    "Fishing",
                    "Gardening",
                    "Geocaching",
                    "Hiking",
                    "Homebrewing",
                    "Jigsaw Puzzles",
                    "Leatherworking",
                    "LEGO Building",
                    "Metal Detecting",
                    "Miniature Painting",
                    "Model Building",
                    "Pen Collecting",
                    "Pottery and Ceramics",
                    "RC Vehicles",
                    "Rock Collecting",
                    "Stamp Collecting",
                    "Tabletop RPGs",
                    "Trading Card Games",
                    "Train Sets",
                    "Vinyl Records",
                    "Wargaming",
                    "Watch Collecting",
                ),
            "Home & Garden" to
                listOf(
                    "Backyard Design",
                    "Bathroom Renovation",
                    "Composting",
                    "Container Gardening",
                    "Curb Appeal",
                    "Deck and Porch",
                    "DIY Home Improvement",
                    "Farmhouse Style",
                    "Flooring Ideas",
                    "Flower Gardening",
                    "Furniture Design",
                    "Home Automation",
                    "Home Decor",
                    "Home Energy Efficiency",
                    "Home Office Design",
                    "Home Organization",
                    "Home Security Systems",
                    "Home Storage Solutions",
                    "Houseplants",
                    "Indoor Herb Garden",
                    "Interior Design",
                    "Kitchen Remodel",
                    "Landscaping",
                    "Lawn Care",
                    "Lighting Design",
                    "Minimalist Home",
                    "Organic Gardening",
                    "Outdoor Living",
                    "Patio Design",
                    "Raised Bed Gardening",
                    "Small Space Living",
                    "Smart Home",
                    "Sustainable Living",
                    "Vegetable Gardening",
                    "Window Treatments",
                ),
            "Internet Culture & Social Media" to
                listOf(
                    "AI-Generated Content",
                    "Bluesky Social",
                    "Cancel Culture",
                    "Content Creation",
                    "Content Moderation",
                    "Creator Economy",
                    "Deepfakes",
                    "Digital Privacy",
                    "Digital Wellness",
                    "Discord Servers",
                    "Fan Culture",
                    "Influencer Marketing",
                    "Instagram Reels",
                    "Internet Celebrities",
                    "Livestreaming",
                    "Mastodon Fediverse",
                    "Online Communities",
                    "Online Harassment",
                    "Online Memes",
                    "Online Misinformation",
                    "Podcasting",
                    "Reddit Communities",
                    "Screen Time",
                    "Social Media Algorithms",
                    "Social Media Influencers",
                    "Social Media Marketing",
                    "Social Media Regulation",
                    "Substack Newsletters",
                    "Threads App",
                    "TikTok Trends",
                    "Twitch Streaming",
                    "Viral Videos",
                    "Virtual Influencers",
                    "YouTube Creators",
                    "YouTube Shorts",
                ),
            "Law & Legal" to
                listOf(
                    "AI Regulation",
                    "Antitrust Law",
                    "Bankruptcy Law",
                    "Civil Rights Law",
                    "Class Action Lawsuits",
                    "Constitutional Law",
                    "Consumer Protection",
                    "Copyright Law",
                    "Corporate Law",
                    "Criminal Justice Reform",
                    "Criminal Law",
                    "Cybersecurity Law",
                    "Data Privacy",
                    "Death Penalty",
                    "Election Law",
                    "Employment Law",
                    "Environmental Law",
                    "Family Law",
                    "First Amendment",
                    "Healthcare Law",
                    "Human Rights Law",
                    "Immigration Law",
                    "Intellectual Property",
                    "International Law",
                    "Judicial Nominations",
                    "Legal Technology",
                    "Maritime Law",
                    "Military Law",
                    "Patent Law",
                    "Police Reform",
                    "Privacy Law",
                    "Real Estate Law",
                    "Securities Law",
                    "Supreme Court",
                    "Tax Law",
                    "Tech Regulation",
                    "Trade Law",
                    "Trademark Law",
                    "White Collar Crime",
                ),
            "Lifestyle" to
                listOf(
                    "City Living",
                    "Cottagecore",
                    "Cozy Living",
                    "Dating",
                    "Decluttering",
                    "Digital Detox",
                    "Digital Nomad",
                    "Downsizing",
                    "Expat Life",
                    "Frugal Living",
                    "Home Organization",
                    "Homesteading",
                    "Hygge",
                    "Intentional Living",
                    "Life Hacks",
                    "Life Transitions",
                    "Luxury Lifestyle",
                    "Mindful Living",
                    "Minimalism",
                    "Minimalist Wardrobe",
                    "Morning Routines",
                    "Off-Grid Living",
                    "Personal Development",
                    "Relationships",
                    "Remote Work Lifestyle",
                    "Retirement Living",
                    "Rural Living",
                    "Self-Improvement",
                    "Simple Living",
                    "Slow Living",
                    "Solo Living",
                    "Suburban Living",
                    "Sustainable Living",
                    "Tiny Houses",
                    "Van Life",
                    "Work-Life Balance",
                    "Zero Waste Living",
                ),
            "Military & Defense" to
                listOf(
                    "Air Defense Systems",
                    "Arms Trade and Weapons Sales",
                    "Coast Guard",
                    "Counter-Terrorism",
                    "Cybersecurity Defense",
                    "Defense Budget and Spending",
                    "Defense Contractors",
                    "Defense Industry News",
                    "Defense Policy and Strategy",
                    "Electronic Warfare",
                    "Fighter Jets and Combat Aircraft",
                    "Homeland Security",
                    "Hypersonic Weapons",
                    "Military Artificial Intelligence",
                    "Military Cyber Operations",
                    "Military Drones and UAVs",
                    "Military Intelligence",
                    "Military Recruitment",
                    "Military Technology",
                    "Military Veterans",
                    "Missile Defense",
                    "National Guard",
                    "NATO Alliance",
                    "Naval Warfare",
                    "Nuclear Weapons and Deterrence",
                    "Pentagon News",
                    "Space Force",
                    "Special Operations Forces",
                    "Submarines and Undersea Warfare",
                    "U.S. Air Force",
                    "U.S. Army",
                    "U.S. Marine Corps",
                    "U.S. Navy",
                    "Veterans Affairs and Benefits",
                    "War and Conflict Updates",
                ),
            "Music" to
                listOf(
                    "Album Reviews",
                    "Alternative Music",
                    "Band Interviews",
                    "Blues Music",
                    "Classical Music",
                    "Concert Tours",
                    "Country Music",
                    "DJing",
                    "Electronic Music",
                    "Film Scores",
                    "Folk Music",
                    "Grammy Awards",
                    "Guitar",
                    "Heavy Metal Music",
                    "Hip-Hop Music",
                    "Indie Music",
                    "Jazz Music",
                    "K-Pop",
                    "Latin Music",
                    "Music Charts",
                    "Music Education",
                    "Music Festivals",
                    "Music Industry News",
                    "Music Production",
                    "Music Streaming",
                    "Music Technology",
                    "Music Videos",
                    "New Music Releases",
                    "Opera",
                    "Piano",
                    "Pop Music",
                    "Punk Music",
                    "R&B Music",
                    "Reggae Music",
                    "Rock Music",
                    "Songwriting",
                    "Soul Music",
                    "Vinyl Records",
                    "World Music",
                ),
            "News & Politics" to
                listOf(
                    "Asia Pacific Politics",
                    "Civil Rights",
                    "Climate Policy",
                    "Congress",
                    "Defense Policy",
                    "Diplomacy",
                    "Economic Policy",
                    "Education Policy",
                    "Elections",
                    "European Politics",
                    "Foreign Policy",
                    "Geopolitics",
                    "Government Accountability",
                    "Gun Policy",
                    "Healthcare Policy",
                    "House of Representatives",
                    "Immigration",
                    "Intelligence Community",
                    "Investigative Journalism",
                    "Labor Politics",
                    "Local News",
                    "Media Criticism",
                    "Middle East Politics",
                    "Midterm Elections",
                    "National Security",
                    "NATO",
                    "Policy Analysis",
                    "Political Campaigns",
                    "Political Corruption",
                    "Polling",
                    "Presidential Elections",
                    "Senate",
                    "State Politics",
                    "Supreme Court",
                    "Trade Policy",
                    "United Nations",
                    "US Politics",
                    "White House",
                    "World News",
                ),
            "Parenting" to
                listOf(
                    "ADHD in Children",
                    "Adoption and Foster Care",
                    "Baby Sleep Training",
                    "Back to School",
                    "Blended Families",
                    "Breastfeeding",
                    "Bullying Prevention",
                    "Child Custody",
                    "Child Development Milestones",
                    "Child Nutrition",
                    "Child Safety",
                    "Childhood Anxiety",
                    "Childhood Vaccinations",
                    "Children and Reading",
                    "Co-Parenting",
                    "Daycare and Childcare",
                    "Discipline and Positive Parenting",
                    "Family Activities",
                    "Family Travel with Kids",
                    "Homeschooling",
                    "Kids and Sports",
                    "Newborn Care",
                    "Parental Mental Health",
                    "Parenting Teens and Social Media",
                    "Postpartum Depression",
                    "Potty Training",
                    "Pregnancy and Prenatal Care",
                    "Preschool Readiness",
                    "Preteen Parenting",
                    "School-Age Children",
                    "Screen Time and Kids",
                    "Sibling Rivalry",
                    "Single Parenting",
                    "Special Needs Parenting",
                    "Teenage Parenting",
                    "Toddler Development",
                    "Work-Life Balance for Parents",
                ),
            "Pets & Animals" to
                listOf(
                    "Animal Rescue & Shelters",
                    "Animal Rights",
                    "Animal Science & Research",
                    "Animal Welfare",
                    "Backyard Chickens",
                    "Cat Behavior",
                    "Cats",
                    "Coral Reefs & Marine Conservation",
                    "Dog Breeds",
                    "Dog Training",
                    "Dogs",
                    "Endangered Species",
                    "Exotic Pets",
                    "Freshwater Aquarium Fish",
                    "Horses & Equestrian",
                    "Insects & Pollinators",
                    "Livestock & Farm Animals",
                    "Marine Life",
                    "Pet Adoption",
                    "Pet Birds",
                    "Pet Grooming",
                    "Pet Health",
                    "Pet Industry & Products",
                    "Pet Insurance",
                    "Pet Nutrition",
                    "Pet Travel",
                    "Rabbits",
                    "Reptiles & Amphibians",
                    "Service Animals & Therapy Pets",
                    "Small Pets & Rodents",
                    "Veterinary Medicine",
                    "Wildlife Conservation",
                    "Wildlife Photography",
                    "Zoos & Aquariums",
                ),
            "Philosophy" to
                listOf(
                    "Absurdism",
                    "Aesthetics",
                    "AI Ethics",
                    "Analytic Philosophy",
                    "Ancient Philosophy",
                    "Bioethics",
                    "Buddhism Philosophy",
                    "Confucianism",
                    "Consciousness Studies",
                    "Continental Philosophy",
                    "Critical Theory",
                    "Eastern Philosophy",
                    "Environmental Ethics",
                    "Epistemology",
                    "Ethics",
                    "Existentialism",
                    "Feminist Philosophy",
                    "Free Will",
                    "Hermeneutics",
                    "Logic",
                    "Metaphysics",
                    "Moral Philosophy",
                    "Nihilism",
                    "Phenomenology",
                    "Philosophy of Education",
                    "Philosophy of History",
                    "Philosophy of Language",
                    "Philosophy of Law",
                    "Philosophy of Mind",
                    "Philosophy of Religion",
                    "Philosophy of Science",
                    "Philosophy of Technology",
                    "Political Philosophy",
                    "Postmodernism",
                    "Pragmatism",
                    "Social Justice Philosophy",
                    "Stoicism",
                    "Taoism",
                    "Utilitarianism",
                    "Virtue Ethics",
                ),
            "Photography" to
                listOf(
                    "Abstract Photography",
                    "Adobe Lightroom",
                    "Analog Photography",
                    "Architecture Photography",
                    "Astrophotography",
                    "Black and White Photography",
                    "Camera Gear",
                    "Candid Photography",
                    "Concert Photography",
                    "Darkroom Printing",
                    "Documentary Photography",
                    "Drone Photography",
                    "DSLR Cameras",
                    "Fashion Photography",
                    "Film Photography",
                    "Fine Art Photography",
                    "Food Photography",
                    "Landscape Photography",
                    "Macro Photography",
                    "Mirrorless Cameras",
                    "Mobile Photography",
                    "Nature Photography",
                    "Night Photography",
                    "Photo Contests",
                    "Photo Editing",
                    "Photography Composition",
                    "Photography Exhibitions",
                    "Photojournalism",
                    "Portrait Photography",
                    "Product Photography",
                    "Sports Photography",
                    "Street Photography",
                    "Studio Lighting",
                    "Travel Photography",
                    "Underwater Photography",
                    "Wedding Photography",
                    "Wildlife Photography",
                ),
            "Productivity & Organization" to
                listOf(
                    "Atomic Habits",
                    "Bullet Journaling",
                    "Calendar Management",
                    "Deep Work",
                    "Digital Minimalism",
                    "Digital Productivity Tools",
                    "Eisenhower Matrix",
                    "Email Management",
                    "Focus Techniques",
                    "Getting Things Done",
                    "Goal Setting",
                    "Habit Building",
                    "Habit Tracking",
                    "Inbox Zero",
                    "Kanban Board",
                    "Mind Mapping",
                    "Morning Routine",
                    "Note-Taking Apps",
                    "Notion",
                    "Obsidian",
                    "Personal Automation",
                    "Personal Knowledge Management",
                    "Pomodoro Technique",
                    "Productivity Apps",
                    "Project Planning",
                    "Roam Research",
                    "Second Brain",
                    "Task Management",
                    "Time Management",
                    "Timeboxing",
                    "Todoist",
                    "Weekly Review",
                    "Workflow Automation",
                    "Zapier",
                ),
            "Psychology & Mental Health" to
                listOf(
                    "Addiction Recovery",
                    "ADHD Research",
                    "Adolescent Mental Health",
                    "Anxiety Disorders",
                    "Autism Spectrum",
                    "Behavioral Psychology",
                    "Bipolar Disorder",
                    "Burnout Prevention",
                    "Child Psychology",
                    "Clinical Psychology",
                    "Cognitive Behavioral Therapy",
                    "Couples Therapy",
                    "Depression Treatment",
                    "Developmental Psychology",
                    "Eating Disorders",
                    "Emotional Intelligence",
                    "Grief Counseling",
                    "Mental Health Apps",
                    "Mental Health Policy",
                    "Mental Health Stigma",
                    "Mindfulness Meditation",
                    "Neuropsychology",
                    "Neuroscience Research",
                    "Obsessive Compulsive Disorder",
                    "Perinatal Mental Health",
                    "Personality Disorders",
                    "Positive Psychology",
                    "Psychopharmacology",
                    "Psychotherapy Techniques",
                    "PTSD Recovery",
                    "Schizophrenia Research",
                    "Sleep Psychology",
                    "Social Psychology",
                    "Stress Management",
                    "Substance Abuse Treatment",
                    "Trauma Therapy",
                    "Workplace Mental Health",
                ),
            "Real Estate" to
                listOf(
                    "Affordable Housing",
                    "Commercial Real Estate",
                    "Condo Market",
                    "First Time Home Buyers",
                    "Foreclosures",
                    "Green Building",
                    "Home Appraisal",
                    "Home Buying Tips",
                    "Home Inspections",
                    "Home Insurance",
                    "Home Prices",
                    "Home Renovations",
                    "Homebuilders",
                    "House Flipping",
                    "Housing Market Trends",
                    "Industrial Real Estate",
                    "Luxury Real Estate",
                    "Mortgage Rates",
                    "Multifamily Housing",
                    "Office Real Estate",
                    "Property Management",
                    "Property Taxes",
                    "Real Estate Agents",
                    "Real Estate Auctions",
                    "Real Estate Crowdfunding",
                    "Real Estate Development",
                    "Real Estate Investing",
                    "Real Estate Law",
                    "Real Estate Market Forecast",
                    "Real Estate Technology",
                    "REITs",
                    "Rental Market",
                    "Reverse Mortgages",
                    "Senior Housing",
                    "Short Term Rentals",
                    "Tiny Homes",
                    "Vacation Rentals",
                    "Zoning and Land Use",
                ),
            "Religion & Spirituality" to
                listOf(
                    "Atheism & Agnosticism",
                    "Biblical Studies",
                    "Buddhism",
                    "Catholicism",
                    "Christianity",
                    "Church & State",
                    "Evangelical Christianity",
                    "Hinduism",
                    "Indigenous & Folk Religions",
                    "Interfaith Dialogue",
                    "Islam",
                    "Jainism",
                    "Judaism",
                    "Kabbalah",
                    "Meditation & Mindfulness",
                    "New Age Spirituality",
                    "Orthodox Christianity",
                    "Pilgrimage & Holy Sites",
                    "Prayer & Devotion",
                    "Religion & Science",
                    "Religious Education",
                    "Religious Freedom",
                    "Religious History",
                    "Religious Holidays & Festivals",
                    "Religious Leadership",
                    "Shia Islam",
                    "Shintoism",
                    "Sikhism",
                    "Spirituality",
                    "Sufism",
                    "Sunni Islam",
                    "Taoism",
                    "Theology",
                    "Tibetan Buddhism",
                    "Zen Buddhism",
                ),
            "Science" to
                listOf(
                    "Astrobiology",
                    "Astrophysics",
                    "Biochemistry",
                    "Biophysics",
                    "Botany",
                    "Cell Biology",
                    "Climate Science",
                    "Computational Biology",
                    "CRISPR Gene Editing",
                    "Ecology",
                    "Epidemiology",
                    "Evolutionary Biology",
                    "Genetics",
                    "Genomics",
                    "Geology",
                    "Immunology",
                    "Marine Biology",
                    "Materials Science",
                    "Microbiology",
                    "Molecular Biology",
                    "Nanotechnology",
                    "Neuroscience",
                    "Nuclear Physics",
                    "Oceanography",
                    "Organic Chemistry",
                    "Paleontology",
                    "Particle Physics",
                    "Pharmacology",
                    "Quantum Mechanics",
                    "Seismology",
                    "Stem Cell Research",
                    "Synthetic Biology",
                    "Virology",
                    "Volcanology",
                    "Zoology",
                ),
            "Space & Astronomy" to
                listOf(
                    "Artemis Program",
                    "Asteroid Mining",
                    "Black Holes",
                    "Blue Origin",
                    "Chinese Space Program",
                    "Cosmology",
                    "Dark Energy",
                    "Dark Matter",
                    "Europa Clipper",
                    "Exoplanets",
                    "Galaxy Formation",
                    "Gravitational Waves",
                    "Hubble Telescope",
                    "Indian Space Program ISRO",
                    "International Space Station",
                    "James Webb Space Telescope",
                    "Lunar Gateway",
                    "Mars Exploration",
                    "Moon Exploration",
                    "NASA",
                    "Neutron Stars",
                    "Planetary Science",
                    "Radio Astronomy",
                    "Rocket Launches",
                    "Satellite Technology",
                    "Solar Flares",
                    "Solar System",
                    "Space Debris",
                    "Space Telescopes",
                    "Space Tourism",
                    "Space Weather",
                    "SpaceX",
                    "Starlink Satellites",
                    "Starship Rocket",
                    "Supernovae",
                ),
            "Sports" to
                listOf(
                    "Archery",
                    "Badminton",
                    "Baseball",
                    "Basketball",
                    "BMX",
                    "Bobsled",
                    "Boxing",
                    "Cricket",
                    "CrossFit",
                    "Curling",
                    "Cycling",
                    "Diving",
                    "Esports",
                    "Fencing",
                    "Field Hockey",
                    "Figure Skating",
                    "Football",
                    "Formula 1",
                    "Golf",
                    "Gymnastics",
                    "Handball",
                    "Hockey",
                    "Horse Racing",
                    "IndyCar",
                    "Lacrosse",
                    "Marathon Running",
                    "MMA",
                    "Motocross",
                    "NASCAR",
                    "Pickleball",
                    "Polo",
                    "Rally Racing",
                    "Rock Climbing",
                    "Rowing",
                    "Rugby",
                    "Sailing",
                    "Skateboarding",
                    "Skiing",
                    "Snowboarding",
                    "Soccer",
                    "Surfing",
                    "Swimming",
                    "Table Tennis",
                    "Tennis",
                    "Track and Field",
                    "Triathlon",
                    "Volleyball",
                    "Water Polo",
                    "Weightlifting",
                    "Wrestling",
                ),
            "Technology" to
                listOf(
                    "3D Printing",
                    "5G Networks",
                    "Artificial Intelligence",
                    "Augmented Reality",
                    "Big Data",
                    "Biotechnology",
                    "Blockchain",
                    "Cloud Computing",
                    "Computer Vision",
                    "Cybersecurity",
                    "Data Science",
                    "Deep Learning",
                    "DevOps",
                    "Digital Privacy",
                    "Drones",
                    "Edge Computing",
                    "Electric Vehicles",
                    "Fintech",
                    "Gaming Technology",
                    "Generative AI",
                    "Internet of Things",
                    "Laptops",
                    "Linux",
                    "Machine Learning",
                    "Mobile App Development",
                    "Nanotechnology",
                    "Natural Language Processing",
                    "Net Neutrality",
                    "Open Source Software",
                    "Programming Languages",
                    "Quantum Computing",
                    "Robotics",
                    "Satellite Internet",
                    "Self-Driving Cars",
                    "Semiconductors",
                    "Smart Home",
                    "Smartphones",
                    "Social Media Platforms",
                    "Software Engineering",
                    "Space Technology",
                    "Streaming Services",
                    "Tech Policy and Regulation",
                    "Tech Startups",
                    "Virtual Reality",
                    "Wearables",
                    "Web Development",
                ),
            "Travel" to
                listOf(
                    "Accessible Travel",
                    "Adventure Travel",
                    "Airlines",
                    "Backpacking",
                    "Beach Vacations",
                    "Budget Travel",
                    "Camping",
                    "City Breaks",
                    "Cruises",
                    "Cultural Tourism",
                    "Digital Nomad",
                    "Eco Tourism",
                    "Family Travel",
                    "Food Tourism",
                    "Hiking Travel",
                    "Hotels",
                    "Island Travel",
                    "Luxury Travel",
                    "Mountain Travel",
                    "National Parks",
                    "Passport and Visa",
                    "Pet Friendly Travel",
                    "Road Trips",
                    "Safari Travel",
                    "Ski Travel",
                    "Solo Travel",
                    "Sustainable Travel",
                    "Train Travel",
                    "Travel Deals",
                    "Travel Gear",
                    "Travel Hacking",
                    "Travel Insurance",
                    "Travel Photography",
                    "Travel Safety",
                    "Travel Technology",
                    "Travel Tips",
                    "Van Life",
                    "Volunteer Travel",
                    "Weekend Getaways",
                    "Wellness Travel",
                ),
            "True Crime" to
                listOf(
                    "Arson Investigation",
                    "Cold Cases",
                    "Court Trials",
                    "Crime Documentary",
                    "Crime Scene Investigation",
                    "Crime Statistics",
                    "Criminal Appeals",
                    "Criminal Investigations",
                    "Criminal Profiling",
                    "Criminal Psychology",
                    "Cybercrime",
                    "Death Row",
                    "DNA Evidence",
                    "Domestic Violence Cases",
                    "Drug Trafficking",
                    "Evidence Tampering",
                    "FBI Investigations",
                    "Financial Fraud",
                    "Forensic Psychology",
                    "Forensic Science",
                    "Gang Violence",
                    "Hate Crimes",
                    "Heists and Robberies",
                    "Human Trafficking",
                    "Identity Theft",
                    "Jury Trials",
                    "Kidnapping Cases",
                    "Missing Persons",
                    "Organized Crime",
                    "Parole and Probation",
                    "Police Misconduct",
                    "Prison Life",
                    "Serial Killers",
                    "True Crime Podcasts",
                    "Unsolved Murders",
                    "Victim Advocacy",
                    "White Collar Crime",
                    "Witness Protection",
                    "Wrongful Convictions",
                ),
            "Weather & Climate" to
                listOf(
                    "Air Quality and Smog",
                    "Arctic Ice and Polar Weather",
                    "Atmospheric Science",
                    "Avalanche Warnings",
                    "Blizzards and Ice Storms",
                    "Climate Change Science",
                    "Climate Data and Records",
                    "Climate Policy",
                    "Coastal Storm Surge",
                    "Drought Conditions",
                    "El Nino and La Nina",
                    "Extreme Heat Waves",
                    "Flash Flooding",
                    "Hurricane Tracking",
                    "Jet Stream Patterns",
                    "Lightning and Hail",
                    "Meteorology Research",
                    "Monsoon Season",
                    "Ocean Temperature Anomalies",
                    "Rainfall and Precipitation",
                    "Record Breaking Temperatures",
                    "Sea Level Rise",
                    "Seasonal Allergy Forecasts",
                    "Severe Thunderstorms",
                    "Tornado Outbreaks",
                    "Tropical Storms",
                    "UV Index and Solar Radiation",
                    "Weather and Aviation Safety",
                    "Weather Emergency Preparedness",
                    "Weather Forecasting",
                    "Weather Radar Technology",
                    "Weather Satellites",
                    "Wildfire Weather",
                    "Wind Storms and Derechos",
                    "Winter Storms",
                ),
            "Wellness & Self-Care" to
                listOf(
                    "Acupuncture",
                    "Aromatherapy",
                    "Ayurveda",
                    "Body Positivity",
                    "Breathwork",
                    "Burnout Recovery",
                    "Chronic Pain Management",
                    "Cold Plunge & Ice Bath",
                    "Digital Detox",
                    "Emotional Wellness",
                    "Fitness Recovery",
                    "Float Therapy",
                    "Forest Bathing",
                    "Gratitude Practice",
                    "Gut Health",
                    "Herbal Remedies",
                    "Holistic Health",
                    "Journaling",
                    "Meditation",
                    "Mental Health Awareness",
                    "Mindful Movement",
                    "Mindfulness",
                    "Nutrition & Clean Eating",
                    "Pilates",
                    "Positive Psychology",
                    "Reiki & Energy Healing",
                    "Sauna Therapy",
                    "Self-Care Routines",
                    "Skin Care Rituals",
                    "Sleep Health",
                    "Sleep Hygiene",
                    "Sound Healing",
                    "Spa & Wellness",
                    "Stress Management",
                    "Stretching & Mobility",
                    "Tai Chi",
                    "Wellness Retreats",
                    "Wellness Technology",
                    "Work-Life Balance",
                    "Yoga",
                ),
        )
    val languages =
        listOf(
            "en" to "English",
            "es" to "Español",
            "fr" to "Français",
            "de" to "Deutsch",
            "it" to "Italiano",
            "pt" to "Português",
            "ja" to "日本語",
            "ko" to "한국어",
            "zh" to "中文",
            "hi" to "हिन्दी",
            "ar" to "العربية",
            "ru" to "Русский",
        )
}
