"""Feed import models: OPML import/export and OAuth token management."""

import base64
import datetime
import pickle
from xml.etree.ElementTree import Comment, Element, SubElement, tostring

import mongoengine as mongo
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from lxml import etree
from mongoengine.queryset import OperationError
from oauth2client.client import Error as OAuthError

import vendor.opml as opml
from apps.reader.models import UserSubscription, UserSubscriptionFolders
from apps.rss_feeds.models import DuplicateFeed, Feed
from utils import json_functions as json
from utils import log as logging
from utils import urlnorm
from utils.feed_functions import add_object_to_folder, timelimit


class OAuthToken(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    session_id = models.CharField(max_length=50, null=True, blank=True)
    uuid = models.CharField(max_length=50, null=True, blank=True)
    remote_ip = models.CharField(max_length=50, null=True, blank=True)
    request_token = models.CharField(max_length=50)
    request_token_secret = models.CharField(max_length=50)
    access_token = models.CharField(max_length=50)
    access_token_secret = models.CharField(max_length=50)
    credential = models.TextField(null=True, blank=True)
    created_date = models.DateTimeField(default=datetime.datetime.now)


class Importer:
    def clear_feeds(self):
        UserSubscription.objects.filter(user=self.user).delete()

    def clear_folders(self):
        UserSubscriptionFolders.objects.filter(user=self.user).delete()

    def get_folders(self):
        self.usf, _ = UserSubscriptionFolders.objects.get_or_create(
            user=self.user, defaults={"folders": "[]"}
        )
        return json.decode(self.usf.folders)


class OPMLExporter(Importer):
    def __init__(self, user):
        self.user = user
        self.fetch_feeds()

    def process(self, verbose=False):
        now = str(datetime.datetime.now())

        root = Element("opml")
        root.set("version", "1.1")
        root.append(Comment("Generated by NewsBlur - newsblur.com"))

        head = SubElement(root, "head")
        title = SubElement(head, "title")
        title.text = "NewsBlur Feeds"
        dc = SubElement(head, "dateCreated")
        dc.text = now
        dm = SubElement(head, "dateModified")
        dm.text = now
        folders = self.get_folders()
        body = SubElement(root, "body")
        self.process_outline(body, folders, verbose=verbose)
        return tostring(root, encoding="utf-8", method="xml")

    def process_outline(self, body, folders, verbose=False):
        for obj in folders:
            if isinstance(obj, int) and obj in self.feeds:
                feed = self.feeds[obj]
                if verbose:
                    print("     ---> Adding feed: %s - %s" % (feed["id"], feed["feed_title"][:30]))
                feed_attrs = self.make_feed_row(feed)
                body.append(Element("outline", feed_attrs))
            elif isinstance(obj, dict):
                for folder_title, folder_objs in list(obj.items()):
                    if verbose:
                        print(" ---> Adding folder: %s" % folder_title)
                    folder_element = Element("outline", {"text": folder_title, "title": folder_title})
                    body.append(self.process_outline(folder_element, folder_objs, verbose=verbose))
        return body

    def make_feed_row(self, feed):
        feed_attrs = {
            "text": feed["feed_title"],
            "title": feed["feed_title"],
            "type": "rss",
            "version": "RSS",
            "htmlUrl": feed["feed_link"] or "",
            "xmlUrl": feed["feed_address"] or "",
        }
        return feed_attrs

    def fetch_feeds(self):
        subs = UserSubscription.objects.filter(user=self.user)
        self.feeds = []
        for sub in subs:
            try:
                self.feeds.append((sub.feed_id, sub.canonical()))
            except Feed.DoesNotExist:
                continue
        self.feeds = dict(self.feeds)

    @property
    def feed_count(self):
        return len(self.feeds)


class OPMLImporter(Importer):
    def __init__(self, opml_xml, user):
        self.user = user
        self.opml_xml = opml_xml

    @staticmethod
    def get_outline_attr(item, *attrs):
        for attr in attrs:
            try:
                return getattr(item, attr)
            except AttributeError:
                continue
        return None

    def try_processing(self):
        # Disable timeout in test environment
        if getattr(settings, "TEST_DEBUG", False):
            folders = self.process()
            return folders

        @timelimit(10)
        def _timed_process():
            return self.process()

        folders = _timed_process()
        return folders

    def process(self):
        # self.clear_feeds()

        outline = opml.from_string(self.opml_xml)
        folders = self.get_folders()
        try:
            folders = self.process_outline(outline, folders)
        except AttributeError:
            folders = None
        else:
            # self.clear_folders()
            self.usf.folders = json.encode(folders)
            self.usf.save()

        return folders

    def process_outline(self, outline, folders, in_folder=""):
        for item in outline:
            xml_url = self.get_outline_attr(item, "xmlUrl", "xmlURL")
            if not xml_url and (hasattr(item, "text") or hasattr(item, "title")):
                folder = item
                title = getattr(item, "text", None) or getattr(item, "title", None)
                # if hasattr(folder, 'text'):
                #     logging.info(' ---> [%s] ~FRNew Folder: %s' % (self.user, folder.text))
                obj = {title: []}
                folders = add_object_to_folder(obj, in_folder, folders)
                folders = self.process_outline(folder, folders, title)
            elif xml_url:
                feed = item
                html_url = self.get_outline_attr(feed, "htmlUrl", "htmlURL")
                # If feed title matches what's in the DB, don't override it on subscription.
                feed_title = getattr(feed, "title", None) or getattr(feed, "text", None)
                if not feed_title:
                    feed_title = html_url or xml_url
                    user_feed_title = None
                else:
                    user_feed_title = feed_title

                try:
                    folders = self.process_feed(
                        xml_url, html_url, feed_title, user_feed_title, folders, in_folder
                    )
                except Exception as e:
                    logging.error(" ---> ~FROPML import skipping feed %s: %s" % (xml_url, e))

        return folders

    # apps/feed_import/models.py
    # NewsBlur-internal feed addresses that must never be re-created as new feeds on
    # import. Email newsletters (newsletter:<user_id>:...) are user-specific, and web
    # feeds (webfeed:...) are scraped internally. A NewsBlur OPML export writes these
    # addresses out verbatim, so re-importing that export would otherwise mint a
    # duplicate feed for every newsletter/web feed the user already subscribes to.
    INTERNAL_ADDRESS_PREFIXES = (
        "newsletter:",
        "http://newsletter:",
        "https://newsletter:",
        "webfeed:",
    )

    def existing_feed_match(self, feed_address, feed_link, feed_title):
        # Return the feed_id of a subscription the user already had (before this import)
        # that represents the same source, matched by normalized address, then normalized
        # link, then case-insensitive title. Built once and cached; not updated during the
        # import so a fresh account (no prior subs) never de-dupes against itself.
        if getattr(self, "_existing_feed_index", None) is None:
            by_address, by_link, by_title = {}, {}, {}
            subs = UserSubscription.objects.filter(user=self.user).select_related("feed")
            for us in subs:
                feed = us.feed
                if not feed:
                    continue
                address = urlnorm.normalize(feed.feed_address or "")
                link = urlnorm.normalize(feed.feed_link or "")
                title = (feed.feed_title or "").strip().lower()
                if address:
                    by_address.setdefault(address, feed.pk)
                if link:
                    by_link.setdefault(link, feed.pk)
                if title:
                    by_title.setdefault(title, feed.pk)
            self._existing_feed_index = (by_address, by_link, by_title)

        by_address, by_link, by_title = self._existing_feed_index
        if feed_address and feed_address in by_address:
            return by_address[feed_address]
        if feed_link and feed_link in by_link:
            return by_link[feed_link]
        title = (feed_title or "").strip().lower()
        if title and title in by_title:
            return by_title[title]
        return None

    def process_feed(self, xml_url, html_url, feed_title, user_feed_title, folders, in_folder):
        raw_url = (xml_url or "").strip()
        if raw_url.startswith(self.INTERNAL_ADDRESS_PREFIXES):
            # Reuse the user's existing subscription for this internal address rather than
            # creating a duplicate feed; skip entirely if they aren't already subscribed.
            existing = UserSubscription.objects.filter(user=self.user, feed__feed_address=raw_url).first()
            if existing:
                folders = add_object_to_folder(existing.feed_id, in_folder, folders)
            else:
                logging.info(
                    " ---> [%s] ~FROPML import skipping internal feed address: %s" % (self.user, raw_url[:80])
                )
            return folders

        feed_address = urlnorm.normalize(xml_url)
        feed_link = urlnorm.normalize(html_url)
        if not feed_address:
            return folders
        if len(feed_address) > Feed._meta.get_field("feed_address").max_length:
            return folders
        if feed_link and len(feed_link) > Feed._meta.get_field("feed_link").max_length:
            return folders

        # Auto de-dupe on merge: if the user already subscribes to a feed for this same
        # source under a drifted address/link/title, reuse it instead of minting a
        # duplicate. Matching is limited to subscriptions that existed before this import
        # began, so a fresh import (empty account) is never affected.
        existing_feed_id = self.existing_feed_match(feed_address, feed_link, feed_title)
        if existing_feed_id:
            folders = add_object_to_folder(existing_feed_id, in_folder, folders)
            return folders

        # logging.info(' ---> \t~FR%s - %s - %s' % (feed_title, feed_link, feed_address,))
        feed_data = dict(feed_address=feed_address, feed_link=feed_link, feed_title=feed_title)
        # feeds.append(feed_data)

        # See if it exists as a duplicate first
        duplicate_feed = DuplicateFeed.objects.filter(duplicate_address=feed_address)
        if duplicate_feed:
            feed_db = duplicate_feed[0].feed
        else:
            feed_data["active_subscribers"] = 1
            feed_data["num_subscribers"] = 1
            feed_db, _ = Feed.find_or_create(
                feed_address=feed_address, feed_link=feed_link, defaults=dict(**feed_data)
            )

        if user_feed_title == feed_db.feed_title:
            user_feed_title = None

        try:
            us = UserSubscription.objects.get(feed=feed_db, user=self.user)
        except UserSubscription.DoesNotExist:
            us = None

        if not us:
            us = UserSubscription(
                feed=feed_db,
                user=self.user,
                needs_unread_recalc=True,
                mark_read_date=datetime.datetime.utcnow() - datetime.timedelta(days=1),
                active=self.user.profile.is_premium,
                user_title=user_feed_title,
            )
            us.save()

        if self.user.profile.is_premium and not us.active:
            us.active = True
            us.save()
        if not us.needs_unread_recalc:
            us.needs_unread_recalc = True
            us.save()

        folders = add_object_to_folder(feed_db.pk, in_folder, folders)
        return folders

    def count_feeds_in_opml(self):
        opml_count = len(opml.from_string(self.opml_xml))
        sub_count = UserSubscription.objects.filter(user=self.user).count()
        return max(sub_count, opml_count)


class UploadedOPML(mongo.Document):
    user_id = mongo.IntField()
    opml_file = mongo.StringField()
    upload_date = mongo.DateTimeField(default=datetime.datetime.now)

    def __str__(self):
        user = User.objects.get(pk=self.user_id)
        return "%s: %s characters" % (user.username, len(self.opml_file))

    meta = {
        "collection": "uploaded_opml",
        "allow_inheritance": False,
        "order": "-upload_date",
        "indexes": ["user_id", "-upload_date"],
    }
