// Archive Assistant streaming handler -- relays AI-powered archive search
// responses from Redis PubSub to the client via Socket.IO.
// Generated by CoffeeScript 2.6.1
(function() {
  var handle_archive_assistant_message, log;

  log = require('./log.js');

  // Handler for Archive Assistant streaming messages from Redis PubSub
  handle_archive_assistant_message = (socket, channel, message) => {
    var conversation_id, data, error, message_type, payload, prefix, query_id;
    prefix = 'archive_assistant:';
    if (!(typeof message === 'string' && message.startsWith(prefix))) {
      return false;
    }
    try {
      payload = message.substring(prefix.length);
      data = JSON.parse(payload);
    } catch (error1) {
      error = error1;
      log.debug(`Invalid archive_assistant payload on ${channel}: ${error}`);
      return true;
    }
    message_type = data.type;
    query_id = data.query_id || '';
    conversation_id = data.conversation_id || '';
    if (!query_id) {
      log.debug(`Archive Assistant message missing query_id: ${message}`);
      return true;
    }
    switch (message_type) {
      case 'start':
        log.debug(`archive_assistant:start ${query_id}`);
        socket.emit('archive_assistant:start', {
          query_id: query_id,
          conversation_id: conversation_id
        });
        break;
      case 'chunk':
        socket.emit('archive_assistant:chunk', {
          query_id: query_id,
          conversation_id: conversation_id,
          content: data.content || ''
        });
        break;
      case 'tool_call':
        log.debug(`archive_assistant:tool_call ${query_id} ${data.tool}`);
        socket.emit('archive_assistant:tool_call', {
          query_id: query_id,
          conversation_id: conversation_id,
          tool: data.tool || '',
          input: data.input || {}
        });
        break;
      case 'tool_result':
        log.debug(`archive_assistant:tool_result ${query_id} ${data.tool}: ${data.summary}, preview=${data.preview ? data.preview.length + ' items' : 'none'}`);
        socket.emit('archive_assistant:tool_result', {
          query_id: query_id,
          conversation_id: conversation_id,
          tool: data.tool || '',
          summary: data.summary || '',
          preview: data.preview || null
        });
        break;
      case 'complete':
        log.debug(`archive_assistant:complete ${query_id}`);
        socket.emit('archive_assistant:complete', {
          query_id: query_id,
          conversation_id: conversation_id,
          duration_ms: data.duration_ms || 0,
          tokens_used: data.tokens_used || 0
        });
        break;
      case 'error':
        log.info(`archive_assistant:error ${query_id}: ${data.error}`);
        socket.emit('archive_assistant:error', {
          query_id: query_id,
          conversation_id: conversation_id,
          error: data.error || 'Unknown error'
        });
        break;
      case 'truncated':
        log.debug(`archive_assistant:truncated ${query_id}`);
        socket.emit('archive_assistant:truncated', {
          query_id: query_id,
          conversation_id: conversation_id,
          reason: data.reason || 'premium_required'
        });
        break;
      default:
        log.debug(`Unknown archive_assistant message type: ${message_type}`);
    }
    return true; // Message was handled
  };

  module.exports = {handle_archive_assistant_message};

}).call(this);
