// Generated by CoffeeScript 2.6.1
(function() {
  var handle_ask_ai_message, log;

  log = require('./log.js');

  // Handler for Ask AI streaming messages from Redis PubSub
  handle_ask_ai_message = (socket, channel, message) => {
    var data, error, message_type, payload, prefix, question_id, request_id, story_hash;
    prefix = 'ask_ai:';
    if (!(typeof message === 'string' && message.startsWith(prefix))) {
      return false;
    }
    try {
      payload = message.substring(prefix.length);
      data = JSON.parse(payload);
    } catch (error1) {
      error = error1;
      log.debug(`Invalid ask_ai payload on ${channel}: ${error}`);
      return true;
    }
    message_type = data.type;
    story_hash = data.story_hash;
    question_id = data.question_id || '';
    request_id = data.request_id || '';
    if (!story_hash) {
      log.debug(`Ask AI message missing story hash: ${message}`);
      return true;
    }
    switch (message_type) {
      case 'start':
        log.debug(`ask_ai:start ${story_hash} ${question_id}`);
        socket.emit('ask_ai:start', {
          story_hash: story_hash,
          question_id: question_id,
          request_id: request_id
        });
        break;
      case 'chunk':
        socket.emit('ask_ai:chunk', {
          story_hash: story_hash,
          question_id: question_id,
          request_id: request_id,
          chunk: data.chunk || ''
        });
        break;
      case 'tool_call':
        log.debug(`ask_ai:tool_call ${story_hash} ${data.tool}`);
        socket.emit('ask_ai:tool_call', {
          story_hash: story_hash,
          question_id: question_id,
          request_id: request_id,
          tool: data.tool || '',
          input: data.input || {}
        });
        break;
      case 'tool_result':
        log.debug(`ask_ai:tool_result ${story_hash} ${data.tool}: ${data.summary}`);
        socket.emit('ask_ai:tool_result', {
          story_hash: story_hash,
          question_id: question_id,
          request_id: request_id,
          tool: data.tool || '',
          summary: data.summary || ''
        });
        break;
      case 'complete':
        log.debug(`ask_ai:complete ${story_hash} ${question_id}`);
        socket.emit('ask_ai:complete', {
          story_hash: story_hash,
          question_id: question_id,
          request_id: request_id
        });
        break;
      case 'usage':
        socket.emit('ask_ai:usage', {
          story_hash: story_hash,
          question_id: question_id,
          request_id: request_id,
          message: data.message || ''
        });
        break;
      case 'error':
        log.info(`ask_ai:error ${story_hash} ${question_id}: ${data.error}`);
        socket.emit('ask_ai:error', {
          story_hash: story_hash,
          question_id: question_id,
          request_id: request_id,
          error: data.error || 'Unknown error'
        });
        break;
      default:
        log.debug(`Unknown ask_ai message type: ${message_type}`);
    }
    return true; // Message was handled
  };

  module.exports = {handle_ask_ai_message};

}).call(this);
