// Generated by CoffeeScript 2.6.1
(function() {
  var handle_briefing_message, log;

  log = require('./log.js');

  // Handler for briefing generation progress messages from Redis PubSub
  handle_briefing_message = (socket, channel, message) => {
    var data, message_type, payload, prefix;
    prefix = 'briefing:';
    if (typeof message !== 'string' || !message.startsWith(prefix)) {
      return false;
    }
    try {
      payload = message.substring(prefix.length);
      data = JSON.parse(payload);
    } catch (error) {
      log.debug(`Invalid briefing payload on ${channel}: ${error}`);
      return true;
    }
    message_type = data.type;
    switch (message_type) {
      case 'start':
        log.debug(`briefing:start for ${channel}`);
        socket.emit('briefing:start', {});
        break;
      case 'progress':
        log.debug(`briefing:progress ${data.step} for ${channel}`);
        socket.emit('briefing:progress', {
          step: data.step || '',
          message: data.message || ''
        });
        break;
      case 'complete':
        log.debug(`briefing:complete for ${channel}`);
        socket.emit('briefing:complete', {});
        break;
      case 'error':
        log.info(`briefing:error for ${channel}: ${data.error}`);
        socket.emit('briefing:error', {
          error: data.error || 'Unknown error'
        });
        break;
      default:
        log.debug(`Unknown briefing message type: ${message_type}`);
    }
    return true;
  };

  module.exports = {handle_briefing_message};

}).call(this);
