// Generated by CoffeeScript 2.6.1
(function() {
  var handle_global_search_message, log;

  log = require('./log.js');

  handle_global_search_message = (socket, channel, message) => {
    var data, error, message_type, payload, prefix, search_id;
    prefix = 'global_search:';
    if (!(typeof message === 'string' && message.startsWith(prefix))) {
      return false;
    }
    try {
      payload = message.substring(prefix.length);
      data = JSON.parse(payload);
    } catch (error1) {
      error = error1;
      log.debug(`Invalid global_search payload on ${channel}: ${error}`);
      return true;
    }
    message_type = data.type;
    search_id = data.search_id || '';
    switch (message_type) {
      case 'results':
        socket.emit('global_search:results', {
          search_id: search_id,
          stories: data.stories || [],
          feeds: data.feeds || {},
          chunk_index: data.chunk_index,
          total_chunks: data.total_chunks
        });
        break;
      case 'complete':
        log.debug(`global_search:complete ${search_id}`);
        socket.emit('global_search:complete', {
          search_id: search_id
        });
        break;
      case 'error':
        log.info(`global_search:error ${search_id}: ${data.error}`);
        socket.emit('global_search:error', {
          search_id: search_id,
          error: data.error || 'Unknown error'
        });
        break;
      default:
        log.debug(`Unknown global_search message type: ${message_type}`);
    }
    return true;
  };

  module.exports = {handle_global_search_message};

}).call(this);
