// Generated by CoffeeScript 2.6.1
(function() {
  var debug, info;

  info = function(username, message) {
    var timestamp;
    timestamp = new Date().toISOString().replace(/T/, ' ').replace(/\..+/, '');
    return console.log(`[${timestamp}]  ---> [${username}] ${message}`);
  };

  debug = function(message) {
    var timestamp;
    timestamp = new Date().toISOString().replace(/T/, ' ').replace(/\..+/, '');
    return console.log(`[${timestamp}]  ---> ${message}`);
  };

  exports.info = info;

  exports.debug = debug;

}).call(this);
