// Generated by CoffeeScript 1.8.0
(function() {
  var info;

  info = function(username, message) {
    var timestamp;
    timestamp = new Date().toISOString().replace(/T/, ' ').replace(/\..+/, '');
    return console.log("[" + timestamp + "]  ---> [" + username + "] " + message);
  };

  exports.info = info;

}).call(this);
