// Generated by CoffeeScript 1.8.0
(function() {
  var REDIS_SERVER, SECURE, app, certificate, fs, handler, io, log, options, privateKey, redis;

  fs = require('fs');

  redis = require('redis');

  log = require('./log.js');

  REDIS_SERVER = process.env.NODE_ENV === 'development' ? 'localhost' : 'db_redis_pubsub';

  SECURE = !!process.env.NODE_SSL;

  app = require('http').createServer(handler);

  if (SECURE) {
    privateKey = fs.readFileSync('./config/certificates/newsblur.com.key').toString();
    certificate = fs.readFileSync('./config/certificates/newsblur.com.crt').toString();
    options = {
      port: 8889,
      key: privateKey,
      cert: certificate
    };
    io = require('socket.io')(app);
  } else {
    io = require('socket.io')(8888);
  }

  handler = function(req, res) {
    return log.info(null, req, res);
  };

  io.on('connection', function(socket) {
    var ip;
    ip = socket.handshake.headers['X-Forwarded-For'] || socket.handshake.address;
    socket.on('subscribe:feeds', function(feeds, username) {
      var _ref;
      this.feeds = feeds;
      this.username = username;
      log.info(this.username, ("Connecting (" + feeds.length + " feeds, " + ip + "),") + (" (" + io.engine.clientsCount + " connected) ") + (" " + (SECURE ? "(SSL)" : "(non-SSL)")));
      if (!this.username) {
        return;
      }
      socket.on("error", function(err) {
        return console.log(" ---> Error (socket): " + err);
      });
      if ((_ref = socket.subscribe) != null) {
        _ref.end();
      }
      socket.subscribe = redis.createClient(6379, REDIS_SERVER);
      socket.subscribe.on("error", function(err) {
        console.log(" ---> Error: " + err);
        return socket.subscribe.end();
      });
      socket.subscribe.on("connect", (function(_this) {
        return function() {
          socket.subscribe.subscribe(_this.feeds);
          return socket.subscribe.subscribe(_this.username);
        };
      })(this));
      return socket.subscribe.on('message', (function(_this) {
        return function(channel, message) {
          log.info(_this.username, "Update on " + channel + ": " + message);
          if (channel === _this.username) {
            return socket.emit('user:update', channel, message);
          } else {
            return socket.emit('feed:update', channel, message);
          }
        };
      })(this));
    });
    return socket.on('disconnect', function() {
      var _ref, _ref1;
      if ((_ref = socket.subscribe) != null) {
        _ref.end();
      }
      return log.info(this.username, ("Disconnect (" + ((_ref1 = this.feeds) != null ? _ref1.length : void 0) + " feeds, " + ip + "),") + (" there are now " + io.engine.clientsCount + " users. ") + (" " + (SECURE ? "(SSL)" : "(non-SSL)")));
    });
  });

  io.sockets.on('error', function(err) {
    return console.log(" ---> Error (sockets): " + err);
  });

}).call(this);
