// Generated by CoffeeScript 2.6.1
(function() {
  var handle_webfeed_message, log;

  log = require('./log.js');

  // Handler for Web Feed streaming messages from Redis PubSub
  handle_webfeed_message = (socket, channel, message) => {
    var data, message_type, payload, prefix, request_id, url;
    prefix = 'webfeed:';
    if (typeof message !== 'string' || !message.startsWith(prefix)) {
      return false;
    }
    try {
      payload = message.substring(prefix.length);
      data = JSON.parse(payload);
    } catch (error) {
      log.debug(`Invalid webfeed payload on ${channel}: ${error}`);
      return true;
    }
    message_type = data.type;
    url = data.url || '';
    request_id = data.request_id || '';
    switch (message_type) {
      case 'start':
        log.debug(`webfeed:start ${url}`);
        socket.emit('webfeed:start', {
          url: url,
          request_id: request_id
        });
        break;
      case 'variants':
        log.debug(`webfeed:variants ${url} (${(data.variants != null ? data.variants.length : void 0) || 0} variants)`);
        socket.emit('webfeed:variants', {
          url: url,
          request_id: request_id,
          variants: data.variants || [],
          html_hash: data.html_hash || '',
          page_title: data.page_title || '',
          favicon_url: data.favicon_url || ''
        });
        break;
      case 'complete':
        log.debug(`webfeed:complete ${url}`);
        socket.emit('webfeed:complete', {
          url: url,
          request_id: request_id
        });
        break;
      case 'error':
        log.info(`webfeed:error ${url}: ${data.error}`);
        socket.emit('webfeed:error', {
          url: url,
          request_id: request_id,
          error: data.error || 'Unknown error'
        });
        break;
      case 'progress':
        log.debug(`webfeed:progress ${url}: ${data.message}`);
        socket.emit('webfeed:progress', {
          url: url,
          request_id: request_id,
          message: data.message || ''
        });
        break;
      case 'subscribe_update':
        var feed_id = data.feed_id || '';
        var stage = data.stage || '';
        log.debug(`webfeed:subscribe_update feed:${feed_id} stage:${stage}`);
        socket.emit('webfeed:subscribe_update', {
          feed_id: feed_id,
          stage: stage,
          feed: data.feed || null,
          error: data.error || null
        });
        break;
      default:
        log.debug(`Unknown webfeed message type: ${message_type}`);
    }
    return true;
  };

  module.exports = {handle_webfeed_message};

}).call(this);
