---
- name: Register forum in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/forum.json
  when: disable_consul_services_ie_staging is not defined
  notify:
    - reload consul

- name: Allow http
  become: yes
  ufw: rule=allow port=80
  tags: ufw

- name: Allow https
  become: yes
  ufw: rule=allow port=443
  tags: ufw
