from django.urls import re_path

from apps.profile import views

urlpatterns = [
    re_path(r"^get_preferences?/?", views.get_preference),
    re_path(r"^set_preference/?", views.set_preference),
    re_path(r"^set_account_settings/?", views.set_account_settings),
    re_path(r"^get_view_setting/?", views.get_view_setting),
    re_path(r"^set_view_setting/?", views.set_view_setting),
    re_path(r"^clear_view_setting/?", views.clear_view_setting),
    re_path(r"^set_collapsed_folders/?", views.set_collapsed_folders),
    re_path(r"^paypal_form/?", views.paypal_form),
    re_path(r"^paypal_return/?", views.paypal_return, name="paypal-return"),
    re_path(r"^paypal_archive_return/?", views.paypal_archive_return, name="paypal-archive-return"),
    re_path(r"^paypal_pro_return/?", views.paypal_pro_return, name="paypal-pro-return"),
    re_path(r"^stripe_return/?", views.paypal_return, name="stripe-return"),
    re_path(
        r"^switch_stripe_subscription/?", views.switch_stripe_subscription, name="switch-stripe-subscription"
    ),
    re_path(
        r"^switch_paypal_subscription/?", views.switch_paypal_subscription, name="switch-paypal-subscription"
    ),
    re_path(r"^is_premium_archive/?$", views.profile_is_premium_archive, name="profile-is-premium-archive"),
    re_path(r"^is_premium/?$", views.profile_is_premium, name="profile-is-premium"),
    re_path(r"^activate_premium_trial/?", views.activate_premium_trial, name="activate-premium-trial"),
    # re_path(r'^paypal_ipn/?', include('paypal.standard.ipn.urls'), name='paypal-ipn'),
    re_path(r"^paypal_ipn/?", views.paypal_ipn, name="paypal-ipn"),
    re_path(r"^paypal_webhooks/?", views.paypal_webhooks, name="paypal-webhooks"),
    re_path(r"^stripe_form/?", views.stripe_form, name="stripe-form"),
    re_path(r"^stripe_checkout/?", views.stripe_checkout, name="stripe-checkout"),
    re_path(r"^activities/?", views.load_activities, name="profile-activities"),
    re_path(r"^payment_history/?", views.payment_history, name="profile-payment-history"),
    re_path(r"^invoice/(?P<payment_id>\d+)/?$", views.invoice, name="profile-invoice"),
    re_path(r"^cancel_premium/?", views.cancel_premium, name="profile-cancel-premium"),
    re_path(r"^refund_premium/?", views.refund_premium, name="profile-refund-premium"),
    re_path(r"^never_expire_premium/?", views.never_expire_premium, name="profile-never-expire-premium"),
    re_path(r"^upgrade_premium/?", views.upgrade_premium, name="profile-upgrade-premium"),
    re_path(r"^save_ios_receipt/?", views.save_ios_receipt, name="save-ios-receipt"),
    re_path(r"^save_android_receipt/?", views.save_android_receipt, name="save-android-receipt"),
    re_path(r"^update_payment_history/?", views.update_payment_history, name="profile-update-payment-history"),
    re_path(r"^delete_account/?", views.delete_account, name="profile-delete-account"),
    re_path(r"^forgot_password_return/?", views.forgot_password_return, name="profile-forgot-password-return"),
    re_path(r"^forgot_password/?", views.forgot_password, name="profile-forgot-password"),
    re_path(r"^delete_starred_stories/?", views.delete_starred_stories, name="profile-delete-starred-stories"),
    re_path(r"^count_starred_stories/?", views.count_starred_stories, name="profile-count-starred-stories"),
    re_path(r"^count_shared_stories/?", views.count_shared_stories, name="profile-count-shared-stories"),
    re_path(r"^delete_shared_stories/?", views.delete_shared_stories, name="profile-delete-shared-stories"),
    re_path(r"^count_classifiers/?", views.count_classifiers, name="profile-count-classifiers"),
    re_path(r"^delete_classifiers/?", views.delete_classifiers, name="profile-delete-classifiers"),
    re_path(r"^delete_all_sites/?", views.delete_all_sites, name="profile-delete-all-sites"),
    re_path(r"^email_optout/?", views.email_optout, name="profile-email-optout"),
    re_path(r"^ios_subscription_status/?", views.ios_subscription_status, name="profile-ios-subscription-status"),
    re_path(r"debug/?", views.trigger_error, name="trigger-error"),
]
