from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LogoutView
from django.contrib.sitemaps.views import sitemap
from django.urls import include, re_path
from django.views.generic import RedirectView

from apps.mcp import views as mcp_views
from apps.profile import views as profile_views
from apps.reader import views as reader_views
from apps.social import views as social_views
from apps.static import views as static_views
from apps.static.sitemaps import StaticSitemap

admin.autodiscover()

urlpatterns = [
    re_path(r"^$", reader_views.index, name="index"),
    re_path(r"^reader/", include("apps.reader.urls")),
    re_path(r"^ask-ai/", include("apps.ask_ai.urls")),
    re_path(r"^webfeed/", include("apps.webfeed.urls")),
    re_path(r"^welcome/?$", reader_views.welcome_req, name="welcome-page"),
    re_path(r"^add(?:/.*)?$", reader_views.index),
    re_path(r"^try/?", reader_views.index),
    re_path(r"^site/(?P<feed_id>\d+)?", reader_views.index),
    re_path(r"^folder/(?P<folder_name>\d+)?", reader_views.index, name="folder"),
    re_path(r"^saved/(?P<tag_name>\d+)?", reader_views.index, name="saved-stories-tag"),
    re_path(r"^saved/?", reader_views.index),
    re_path(r"^read/?", reader_views.index),
    re_path(r"^trending/?", reader_views.index),
    re_path(r"^archive/?$", reader_views.index),
    re_path(r"^briefing-admin/?$", reader_views.index),
    re_path(r"^briefing/?$", reader_views.index),
    re_path(r"^briefing/(?!stories|preferences|status|generate|admin)", reader_views.index),
    re_path(r"^social/\d+/.*?", reader_views.index),
    re_path(r"^user/.*?", reader_views.index),
    re_path(r"^null/.*?", reader_views.index),
    re_path(r"^story/.*?", reader_views.index),
    re_path(r"^feed/?$", social_views.shared_stories_rss_feed_noid),
    re_path(r"^rss_feeds/", include("apps.rss_feeds.urls")),
    re_path(r"^discover/", include("apps.discover.urls")),
    re_path(r"^analyzer/", include("apps.analyzer.urls")),
    re_path(r"^classifier/", include("apps.analyzer.urls")),
    re_path(r"^folder_rss/", include("apps.profile.urls")),
    re_path(r"^profile/", include("apps.profile.urls")),
    re_path(r"^import/", include("apps.feed_import.urls")),
    re_path(r"^api/", include("apps.api.urls")),
    re_path(r"^api/archive/", include("apps.archive_extension.urls")),
    re_path(r"^archive-assistant/", include("apps.archive_assistant.urls")),
    re_path(r"^recommendations/", include("apps.recommendations.urls")),
    re_path(r"^notifications/?", include("apps.notifications.urls")),
    re_path(r"^media_player/", include("apps.media_player.urls")),
    re_path(r"^statistics/", include("apps.statistics.urls")),
    re_path(r"^social/", include("apps.social.urls")),
    re_path(r"^search/", include("apps.search.urls")),
    re_path(r"^oauth/", include("apps.oauth.urls")),
    re_path(r"^mobile/", include("apps.mobile.urls")),
    re_path(r"^m/", include("apps.mobile.urls")),
    re_path(r"^push/", include("apps.push.urls")),
    re_path(r"^newsletters/", include("apps.newsletters.urls")),
    re_path(r"^categories/", include("apps.categories.urls")),
    re_path(r"^briefing/", include("apps.briefing.urls")),
    re_path(r"^_haproxychk", static_views.haproxy_check),
    re_path(r"^_dbcheck/postgres", static_views.postgres_check),
    re_path(r"^_dbcheck/mongo", static_views.mongo_check),
    re_path(r"^_dbcheck/redis", static_views.redis_check),
    re_path(r"^_dbcheck/elasticsearch", static_views.elasticsearch_check),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^pricing/?$", static_views.pricing, name="pricing"),
    re_path(r"^pricing/premium/?$", static_views.pricing_premium, name="pricing-premium"),
    re_path(r"^pricing/archive/?$", static_views.pricing_archive, name="pricing-archive"),
    re_path(r"^pricing/pro/?$", static_views.pricing_pro, name="pricing-pro"),
    re_path(r"^features/?$", static_views.features, name="features"),
    re_path(
        r"^features/intelligence-training/?$",
        static_views.feature_intelligence_training,
        name="feature-intelligence-training",
    ),
    re_path(r"^features/ask-ai/?$", static_views.feature_ask_ai, name="feature-ask-ai"),
    re_path(r"^features/web-feeds/?$", static_views.feature_web_feeds, name="feature-web-feeds"),
    re_path(r"^features/newsletters/?$", static_views.feature_newsletters, name="feature-newsletters"),
    re_path(r"^features/search/?$", static_views.feature_search, name="feature-search"),
    re_path(r"^features/archive/?$", static_views.feature_archive, name="feature-archive"),
    re_path(r"^features/saved-stories/?$", static_views.feature_saved_stories, name="feature-saved-stories"),
    re_path(r"^features/native-apps/?$", static_views.feature_native_apps, name="feature-native-apps"),
    re_path(r"^features/mcp/?$", static_views.feature_mcp, name="feature-mcp"),
    re_path(r"^features/cli/?$", static_views.feature_cli, name="feature-cli"),
    re_path(r"^features/mcp-cli/?$", static_views.feature_mcp_cli_redirect, name="feature-mcp-cli"),
    re_path(
        r"^features/story-clustering/?$",
        static_views.feature_story_clustering,
        name="feature-story-clustering",
    ),
    re_path(r"^compare/feedly/?", static_views.compare_feedly, name="compare-feedly"),
    re_path(r"^compare/inoreader/?", static_views.compare_inoreader, name="compare-inoreader"),
    re_path(r"^compare/readwise-reader/?", static_views.compare_readwise, name="compare-readwise"),
    re_path(r"^compare/the-old-reader/?", static_views.compare_the_old_reader, name="compare-the-old-reader"),
    re_path(r"^alternative/open-source-rss-reader/?", static_views.alt_open_source, name="alt-open-source"),
    re_path(r"^alternative/self-hosted-rss-reader/?", static_views.alt_self_hosted, name="alt-self-hosted"),
    re_path(r"^alternative/google-reader/?", static_views.alt_google_reader, name="alt-google-reader"),
    re_path(r"^alternative/feedly/?", static_views.alt_feedly, name="alt-feedly"),
    re_path(r"^alternative/inoreader/?", static_views.alt_inoreader, name="alt-inoreader"),
    re_path(r"^compare/feedbin/?", static_views.compare_feedbin, name="compare-feedbin"),
    re_path(
        r"^sitemap\.xml$",
        sitemap,
        {"sitemaps": {"static": StaticSitemap}},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    re_path(r"^about/?", static_views.about, name="about"),
    re_path(r"^faq/?", static_views.faq, name="faq"),
    re_path(r"^api/?$", static_views.api, name="api"),
    re_path(r"^press/?", static_views.press, name="press"),
    re_path(r"^feedback/?", static_views.feedback, name="feedback"),
    re_path(r"^privacy/?", static_views.privacy, name="privacy"),
    re_path(r"^tos/?", static_views.tos, name="tos"),
    re_path(r"^manifest.webmanifest", static_views.webmanifest, name="webmanifest"),
    # MCP OAuth discovery (RFC 8414 / RFC 9728)
    re_path(
        r"^\.well-known/oauth-authorization-server/mcp/?$",
        mcp_views.oauth_authorization_server_metadata,
        name="mcp-oauth-metadata",
    ),
    re_path(
        r"^\.well-known/oauth-protected-resource/mcp/?$",
        mcp_views.oauth_protected_resource_metadata,
        name="mcp-oauth-protected-resource",
    ),
    re_path(
        r"^.well-known/apple-app-site-association",
        static_views.apple_app_site_assoc,
        name="apple-app-site-assoc",
    ),
    re_path(
        r"^.well-known/apple-developer-merchantid-domain-association",
        static_views.apple_developer_merchantid,
        name="apple-developer-merchantid",
    ),
    re_path(
        r"^\.well-known/assetlinks\.json$",
        static_views.assetlinks,
        name="assetlinks",
    ),
    re_path(r"^ios/download/?", static_views.ios_download, name="ios-download"),
    re_path(r"^ios/NewsBlur.plist", static_views.ios_plist, name="ios-download-plist"),
    re_path(r"^ios/NewsBlur.ipa", static_views.ios_ipa, name="ios-download-ipa"),
    re_path(r"^ios/?", static_views.ios, name="ios-static"),
    re_path(r"^iphone/?", static_views.ios),
    re_path(r"^ipad/?", static_views.ios),
    re_path(r"^android/?", static_views.android, name="android-static"),
    re_path(r"^firefox/?", static_views.firefox, name="firefox"),
    re_path(r"zebra/", include("zebra.urls", namespace="zebra")),
    re_path(r"^login/?$", RedirectView.as_view(pattern_name="login", permanent=True)),
    re_path(r"^signup/?$", RedirectView.as_view(pattern_name="signup", permanent=True)),
    re_path(r"^forgot-password/?$", RedirectView.as_view(pattern_name="profile-forgot-password", permanent=True)),
    re_path(r"^refer/(?P<username>[\w.]+)/?$", profile_views.referral_landing, name="referral-landing"),
    re_path(
        r"^gift/(?P<gift_tier>premium|archive|pro)/(?P<username>[\w.]+)/(?P<gift_code>[a-zA-Z0-9]+)/?$",
        profile_views.gift_redeem,
        name="gift-redeem",
    ),
    re_path(r"^account/redeem_code/?$", profile_views.redeem_code, name="redeem-code"),
    re_path(r"^account/login/?$", profile_views.login, name="login"),
    re_path(r"^account/signup/?$", profile_views.signup, name="signup"),
    re_path(r"^account/logout/?$", LogoutView.as_view(next_page="/"), name="logout"),
    re_path(r"^account/ifttt/v1/", include("apps.oauth.urls")),
    re_path(r"^account/", include("oauth2_provider.urls", namespace="oauth2_provider")),
    re_path(r"^monitor/", include("apps.monitor.urls"), name="monitor"),
    re_path(r"^health-check/?", static_views.health_check, name="health-check"),
    re_path("", include("django_prometheus.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
