- name: Start redis-exporter containers
  become: yes
  docker_container:
    name: "{{item.redis_target}}-exporter"
    image: oliver006/redis_exporter:latest
    restart_policy: unless-stopped
    container_default_behavior: no_defaults
    env:
      REDIS_ADDR: "db-{{item.redis_target}}.service.nyc1.consul:6379"
    networks_cli_compatible: yes
    network_mode: default
    networks:
      - name: newsblurnet
    ports:
    - '{{item.port}}:9121'
  with_items:
    - port: 9121
      redis_target: "redis-user"
    - port: 9122
      redis_target: "redis-sessions"
    - port: 9123
      redis_target: "redis-story"
    - port: 9124
      redis_target: "redis-pubsub"

- name: Register redis-exporters in consul
  tags: consul
  become: yes
  template:
    src: consul_service.json
    dest: /etc/consul.d/{{item.redis_target}}-exporter.json
  notify:
    - reload consul
  with_items:
    - port: 9121
      redis_target: "redis-user"
    - port: 9122
      redis_target: "redis-sessions"
    - port: 9123
      redis_target: "redis-story"
    - port: 9124
      redis_target: "redis-pubsub"
