apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsblur-web
  namespace: newsblur
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newsblur-node
  namespace: newsblur
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-celery
  namespace: newsblur
spec:
  replicas: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: newsblur
spec:
  replicas: 2
