---
# tasks file for docker-ce-ansible-role

- name: Remove previous docker installation
  become: yes
  apt:
    name: "{{ item.package }}"
    state: absent
  with_items: "{{ docker_cleanup_packages_Ubuntu }}"

- name: Install prerequisite packages
  become: yes
  apt:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ docker_prerequisite_packages_Ubuntu }}"

- name: Download Docker GPG key
  become: yes
  shell:
    cmd: "curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg"
    creates: /usr/share/keyrings/docker-archive-keyring.gpg
    
- name: Set up the Docker repository with the correct GPG key
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Set up the Docker repository with the correct GPG key
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Set up the Docker repository with the correct GPG key
  become: yes
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: Update APT cache
  become: yes
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker CE and Compose plugin
  become: yes
  apt:
    name:
      - docker-ce
      - docker-compose-plugin
    state: latest
    update_cache: yes
    