---
# tasks file for docker-ce-ansible-role

- name: Install docker-ce (RedHat)
  include_tasks: install-EL.yml
  when: ansible_os_family == 'RedHat'

- name: Install docker-ce (Ubuntu)
  include_tasks: install-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Enable Docker CE service on startup
  service:
    name: docker
    state: started
    enabled: yes

- name: "Add {{ ansible_ssh_user }} to docker group"
  become: yes
  user:
    name: "{{ ansible_ssh_user }}"
    groups: docker
    append: yes

- name: Turn off Docker iptables firewall exclusion
  become: yes
  template:
    src: daemon.json
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: Make docker network for newsblurnet
  become: yes
  docker_network:
    name: newsblurnet
  notify: restart docker
