# Generated by Django 3.1.4 on 2021-01-06 19:27

from django.db import migrations
from django.conf import settings

def remove_mongo_types(apps, schema_editor):
    db = settings.MONGODB.newsblur_dev
    collections = db.collection_names()
    for collection_name in collections:
        collection = db[collection_name]
        print(" ---> %s..." % (collection_name))
        if 'system' in collection_name: continue
        collection.update({}, {"$unset": {"_types": 1}}, multi=True)
        index_information = collection.index_information()
        indexes_to_drop = [key for key, value in index_information.items()
                           if 'types' in value]
        # print(index_information, indexes_)
        for index in indexes_to_drop:
            print(" ---> Dropping mongo index %s on %s..." % (index, collection_name))
            collection.drop_index(index)

class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_mongo_types, migrations.RunPython.noop)
    ]
