# Generated by Django 3.1.10 on 2022-05-17 13:35
# Updated for MongoDB 4.4 compatibility

from django.conf import settings
from django.db import migrations


def set_mongo_feature_compatibility_version(apps, schema_editor):
    # This migration originally set version to 4.0, but MongoDB 4.4 only accepts 4.2 or 4.4
    # We now skip this if we're already at 4.2 or higher
    db = settings.MONGODB.admin
    doc = db.command({"getParameter": 1, "featureCompatibilityVersion": 1})
    old_version = doc["featureCompatibilityVersion"]["version"]
    print(f"\n ---> Current MongoDB featureCompatibilityVersion: {old_version}")

    # Only try to set 4.0 if we're on an older version (which would be pre-4.0)
    # On MongoDB 4.4, valid values are only 4.2 or 4.4, so skip if already >= 4.0
    if old_version in ("4.0", "4.2", "4.4"):
        print(f" ---> MongoDB featureCompatibilityVersion {old_version} is already compatible, skipping")
    else:
        # Only try to set this on MongoDB versions that support 4.0
        new_version = "4.0"
        db.command({"setFeatureCompatibilityVersion": new_version})
        print(f" ---> Updated MongoDB featureCompatibilityVersion: {new_version}")


class Migration(migrations.Migration):
    dependencies = [
        ("rss_feeds", "0002_remove_mongo_types"),
    ]

    operations = [migrations.RunPython(set_mongo_feature_compatibility_version, migrations.RunPython.noop)]
