# Generated by Django 3.1.10 on 2022-01-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0003_auto_20220110_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='pro_subscribers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
