# Generated by Django 3.1.10 on 2022-01-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0004_feed_pro_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='archive_subscribers',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
