# Generated by Django 3.1.10 on 2022-05-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0005_feed_archive_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='fs_size_bytes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
