# Generated by Django 3.1.10 on 2022-05-17 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0006_feed_fs_size_bytes'),
        ('rss_feeds', '0003_mongo_version_4_0'),
    ]

    operations = [
    ]
