# Generated by Django 3.1.10 on 2022-06-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_feeds', '0007_merge_20220517_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='archive_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
