# Generated by Django 3.1.10 on 2025-03-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rss_feeds", "0010_feed_discover_indexed"),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="date_forbidden",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="is_forbidden",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
