# Generated by Django 3.1.10 on 2026-09-14 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rss_feeds", "0013_feed_is_forbidden_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feed",
            name="branch_from_feed",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="rss_feeds.feed"
            ),
        ),
    ]
