package com.newsblur.util;

public enum GestureAction {

    GEST_ACTION_NONE,
    GEST_ACTION_BACK,
    GEST_ACTION_TOGGLE_READ,
    GEST_ACTION_MARKREAD,
    GEST_ACTION_MARKUNREAD,
    GEST_ACTION_SAVE,
    GEST_ACTION_UNSAVE,
    GEST_ACTION_STATISTICS,
    GEST_ACTION_MENU,
    GEST_ACTION_SHARE,
    GEST_ACTION_TOGGLE_SAVE,
    GEST_ACTION_ASK_AI,
    GEST_ACTION_TRAIN,
    GEST_ACTION_NOTIFICATIONS,
    GEST_ACTION_READ_RANGE

}
